/* ============ air_specs.js — real airframe geometry, one row per aircraft ============
   Generated from a per-era spec pass with an adversarial historical audit.
   Consumed by air3d_era.js, which turns each row into a silhouette. Fields are
   documented at the top of that file; len/span are real metres.
                                                                              */
var AIRFRAMES = {
  /* ---- aerial refuelling ----
     Three airliner- and freighter-derived tankers. The shapes are genuinely
     different and should read as different at a glance: the KC-46 is a
     767, low-winged with two big pods; the Il-78 and the YY-20 are military
     freighters, high-winged and T-tailed with four engines. */
  tanker_n: {era:"e20", fac:"nato", role:"tanker", designation:"KC-46A Pegasus", len:50.5, span:48.1, planform:"swept", sweep:31.5, taper:0.28, dihedral:5, prop:"none", engines:2, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  tanker_p: {era:"e80", fac:"pact", role:"tanker", designation:"Il-78M Midas", len:46.6, span:50.5, planform:"swept", sweep:25, taper:0.32, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"t", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  tanker_c: {era:"e00", fac:"pla", role:"tanker", designation:"YY-20 (Y-20U)", len:47.0, span:50.0, planform:"swept", sweep:24, taper:0.33, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"t", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},

  /* Eight engines in four underwing pods, a wing so long it needs outrigger
     gear, and a fin taller than most fighters are long. */
  hbomber_n: {era:"e20", fac:"nato", role:"heavybomber", designation:"B-52H Stratofortress", len:48.5, span:56.4, planform:"swept", sweep:36.5, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  nato_e50_heavybomber: {era:"e50", fac:"nato", role:"heavybomber", designation:"B-52D Stratofortress", len:48.0, span:56.4, planform:"swept", sweep:36.5, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  nato_e60_heavybomber: {era:"e60", fac:"nato", role:"heavybomber", designation:"B-52D Big Belly", len:48.0, span:56.4, planform:"swept", sweep:36.5, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  nato_e80_heavybomber: {era:"e80", fac:"nato", role:"heavybomber", designation:"B-52G Stratofortress", len:48.0, span:56.4, planform:"swept", sweep:36.5, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  nato_e90_heavybomber: {era:"e90", fac:"nato", role:"heavybomber", designation:"B-52H (CALCM)", len:48.5, span:56.4, planform:"swept", sweep:36.5, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  nato_e00_heavybomber: {era:"e00", fac:"nato", role:"heavybomber", designation:"B-52H (JASSM)", len:48.5, span:56.4, planform:"swept", sweep:36.5, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},

  /* Hercules: high wing, four big turboprops, a deep boxy hold and a ramp. */
  airlift_n: {era:"e20", fac:"nato", role:"airlift", designation:"C-130J Super Hercules", len:34.4, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  nato_e50_airlift: {era:"e50", fac:"nato", role:"airlift", designation:"C-130A Hercules", len:29.8, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  nato_e80_airlift: {era:"e80", fac:"nato", role:"airlift", designation:"C-130H Hercules", len:29.8, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},

  /* the gunship is a Hercules that has been given artillery */
  gunshipair_n: {era:"e20", fac:"nato", role:"gunshipair", designation:"AC-130J Ghostrider", len:34.4, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  nato_e60_gunshipair: {era:"e60", fac:"nato", role:"gunshipair", designation:"AC-130A Spectre", len:29.8, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  nato_e80_gunshipair: {era:"e80", fac:"nato", role:"gunshipair", designation:"AC-130H Spectre", len:29.8, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"black"},
  nato_e00_gunshipair: {era:"e00", fac:"nato", role:"gunshipair", designation:"AC-130U Spooky II", len:29.8, span:40.4, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},

  /* Near-straight shoulder wing of huge span for its length, engines flush in the wing roots, and split airbrake pods hanging off the wingtips. */
  kpa_e00_cas: {era:"e00", fac:"kpa", role:"cas", designation:"Su-25K", len:15.5, span:14.4, planform:"straight", sweep:18, taper:0.4, dihedral:0, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Deep curved LERX blending into wide-spaced engine tunnels, twin fins splayed outboard on booms either side of a humped spine. */
  kpa_e00_fighter: {era:"e00", fac:"kpa", role:"fighter", designation:"MiG-29", len:17.3, span:11.4, planform:"trap", sweep:42, taper:0.25, dihedral:-2, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* 707 airliner — low swept wing, four underwing pods, single swept fin — with a 9 m rotodome on two struts above the rear fuselage. */
  nato_e00_awacs: {era:"e00", fac:"nato", role:"awacs", designation:"E-3G", len:46.6, span:44.4, planform:"swept", sweep:35, taper:0.3, dihedral:7, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"single", htail:"low", wingpos:"low", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Long straight untapered wing with drooped tips, two barrel engines slung high on the rear fuselage, and twin fins on the ends of a rectangular tailplane. */
  nato_e00_cas: {era:"e00", fac:"nato", role:"cas", designation:"A-10C", len:16.3, span:17.5, planform:"straight", sweep:3, taper:0.55, dihedral:3, prop:"none", engines:2, engMount:"rearpod", intake:"none", tail:"twinboom", htail:"mid", wingpos:"low", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* Super Hornet outline — sawtooth wing leading edge, rectangular caret intakes, fins canted outward — with fat ALQ-218 pods replacing the wingtip rails. */
  nato_e00_ewair: {era:"e00", fac:"nato", role:"ewair", designation:"EA-18G", len:18.3, span:13.6, planform:"trap", sweep:27, taper:0.3, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"twincant", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.2, camo:"twotone"},
  /* Diamond planform — large canted fins plus oversized slab tailplanes crowding right up against the wing trailing edge, caret intakes flat on the flanks. */
  nato_e00_fighter: {era:"e00", fac:"nato", role:"fighter", designation:"F-22A", len:18.9, span:13.6, planform:"trap", sweep:42, taper:0.2, dihedral:3, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.85, camo:"twotone"},
  /* Standard F-16 shape — chin intake, blended LERX, one fin — but with the slim HARM targeting pod bolted to the intake shoulder. */
  nato_e00_sead: {era:"e00", fac:"nato", role:"sead", designation:"F-16CM", len:15, span:10, planform:"trap", sweep:40, taper:0.2, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"twotone"},
  /* Fat single-engine body with DSI bumps ahead of the intakes; wing and tailplane trailing edges are parallel so the whole planform reads as two nested arrowheads. */
  nato_e00_stealthfighter: {era:"e00", fac:"nato", role:"stealthfighter", designation:"F-35A", len:15.7, span:10.7, planform:"trap", sweep:34, taper:0.25, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"dsi", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.6, camo:"twotone"},
  /* Il-76 with the glazed nose replaced by a solid radome and a refuelling probe, four underwing pods, T-tail, and a rotating saucer on struts. */
  pact_e00_awacs: {era:"e00", fac:"pact", role:"awacs", designation:"A-50U", len:49.6, span:50.5, planform:"swept", sweep:25, taper:0.3, dihedral:-2, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"ttail", htail:"high", wingpos:"high", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Broad shoulder wing bristling with eight pylons, engine trunks flush along the fuselage sides, and clamshell airbrake pods on the wingtips. */
  pact_e00_cas: {era:"e00", fac:"pact", role:"cas", designation:"Su-25SM", len:15.5, span:14.4, planform:"straight", sweep:18, taper:0.4, dihedral:0, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Big canard-less Flanker: ogival LERX, twin upright fins set outboard on the nacelles, and the blunt tail sting projecting between the exhausts. */
  pact_e00_fighter: {era:"e00", fac:"pact", role:"fighter", designation:"Su-35S", len:21.9, span:15.3, planform:"swept", sweep:42, taper:0.2, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"darkgrey"},
  /* Side-by-side two-seat cockpit on a slab-sided box fuselage, square cheek intakes, and swing wings pivoting out of large fixed rectangular gloves. */
  pact_e00_sead: {era:"e00", fac:"pact", role:"sead", designation:"Su-24M", len:22.5, span:17.6, planform:"swing", sweep:16, taper:0.4, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Il-76 airframe — high wing, four underwing pods, T-tail — carrying a fixed disc radome on twin struts above the rear fuselage. */
  pla_e00_awacs: {era:"e00", fac:"pla", role:"awacs", designation:"KJ-2000", len:46.6, span:50.5, planform:"swept", sweep:25, taper:0.3, dihedral:-2, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"ttail", htail:"high", wingpos:"high", fuselage:"airliner", canard:false, rotodome:true, fixedRadome:true, canoe:false, stealth:0, camo:"bluegrey"},
  /* Long tandem two-seat nose ahead of a shoulder wing with pronounced anhedral, boxy cheek intakes and one very tall fin. */
  pla_e00_cas: {era:"e00", fac:"pla", role:"cas", designation:"JH-7A", len:22.3, span:12.7, planform:"swept", sweep:45, taper:0.3, dihedral:-6, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* An-12-derived four-turboprop high-wing hauler disfigured by bulbous cheek radomes either side of the nose and blade farms along the spine. */
  pla_e00_ewair: {era:"e00", fac:"pla", role:"ewair", designation:"Y-8G", len:34, span:38, planform:"straight", sweep:7, taper:0.4, dihedral:1, prop:"turboprop", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Tail-less canard delta: all-moving foreplanes ahead of a big delta, one tall fin, no tailplane at all, single DSI-bumped belly intake. */
  pla_e00_fighter: {era:"e00", fac:"pla", role:"fighter", designation:"J-10B", len:15.5, span:9.8, planform:"delta", sweep:56, taper:0.17, dihedral:-2, prop:"none", engines:1, engMount:"fuselage", intake:"dsi", tail:"single", htail:"none", wingpos:"mid", fuselage:"slim", canard:true, rotodome:false, canoe:false, stealth:0.15, camo:"darkgrey"},
  /* Flanker planform: enormous curved LERX, widely spaced engine nacelles with a flat tail sting between them, twin upright fins. */
  pla_e00_sead: {era:"e00", fac:"pla", role:"sead", designation:"J-16", len:21.9, span:14.7, planform:"swept", sweep:42, taper:0.2, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"darkgrey"},
  /* Exceptionally long chined forebody with canards feeding a cropped delta and small all-moving canted fins — canard delta plus twin fins and no tailplane. */
  pla_e00_stealthfighter: {era:"e00", fac:"pla", role:"stealthfighter", designation:"J-20", len:20.4, span:12.9, planform:"delta", sweep:47, taper:0.16, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"dsi", tail:"twincant", htail:"none", wingpos:"mid", fuselage:"wide", canard:true, rotodome:false, canoe:false, stealth:0.8, camo:"darkgrey"},
  /* Stubby high-wing twin turboprop with four fins spread across a dihedral tailplane to duck the huge 24-foot rotodome. */
  roc_e00_awacs: {era:"e00", fac:"roc", role:"awacs", designation:"E-2K", len:17.6, span:24.6, planform:"straight", sweep:4, taper:0.5, dihedral:3, prop:"turboprop", engines:2, engMount:"pod", intake:"none", tail:"quad", htail:"high", wingpos:"high", fuselage:"wide", canard:false, rotodome:true, canoe:false, stealth:0, camo:"seagrey"},
  /* Small F-16-like planform but with a pair of oval side intakes tucked under the LERX roots — twin-engined and noticeably shorter-winged. */
  roc_e00_cas: {era:"e00", fac:"roc", role:"cas", designation:"F-CK-1C", len:14.2, span:8.5, planform:"trap", sweep:34, taper:0.25, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"twotone"},
  /* Single chin intake under a frameless bubble canopy, blended body with LERX running into a cropped trapezoidal wing and one big fin. */
  roc_e00_fighter: {era:"e00", fac:"roc", role:"fighter", designation:"F-16A MLU", len:15, span:10, planform:"trap", sweep:40, taper:0.2, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"twotone"},
  /* Same broad straight shoulder wing and tip airbrake pods as the Russian Frogfoot, in green-brown KPA camouflage. */
  bomber_k: {era:"e20", fac:"kpa", role:"cas", designation:"Su-25K Frogfoot", len:15.5, span:14.4, planform:"straight", sweep:20, taper:0.45, dihedral:-2, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"single", htail:"mid", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* Fulcrum tunnel-and-LERX layout with squared-off folding wingtips and a deeper humped spine; a notional KPA naval unit, no real airframe exists. */
  cfighter_k: {era:"e20", fac:"kpa", role:"cfighter", designation:"MiG-29K (notional)", len:17.3, span:12, planform:"trap", sweep:42, taper:0.25, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Tiny sharp delta on a plain tube fuselage with a circular nose intake and shock cone — the simplest jet shape in the sky. */
  fighter_k: {era:"e20", fac:"kpa", role:"fighter", designation:"MiG-21bis / Chengdu J-7", len:14.7, span:7.2, planform:"delta", sweep:57, taper:0.17, dihedral:-2, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* 707 airliner with four underwing pods and a 9 m rotodome on two struts above the rear fuselage. */
  awacs_n: {era:"e20", fac:"nato", role:"awacs", designation:"Boeing E-3G Sentry AWACS", len:46.6, span:44.4, planform:"swept", sweep:35, taper:0.3, dihedral:7, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Long straight wing with two fat engine pods high on the rear fuselage between twin tail booms. */
  bomber_n: {era:"e20", fac:"nato", role:"cas", designation:"A-10C Thunderbolt II", len:16.3, span:17.5, planform:"straight", sweep:6, taper:0.5, dihedral:4, prop:"none", engines:2, engMount:"rearpod", intake:"none", tail:"twinboom", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* Stubby high-wing turboprop with four fins on a dihedral tailplane and a 7.3 m rotodome on a single pylon. */
  cawacs_n: {era:"e20", fac:"nato", role:"cawacs", designation:"Northrop Grumman E-2D Advanced Hawkeye", len:17.6, span:24.6, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:2, engMount:"pod", intake:"none", tail:"quad", htail:"mid", wingpos:"high", fuselage:"wide", canard:false, rotodome:true, canoe:false, stealth:0, camo:"seagrey"},
  /* Rectangular fixed side intakes, long sweeping LERX, and twin fins canted outward ahead of the stabilators. */
  cfighter_n: {era:"e20", fac:"nato", role:"cfighter", designation:"Boeing F/A-18E Super Hornet", len:18.3, span:13.6, planform:"trap", sweep:27, taper:0.32, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.15, camo:"twotone"},
  /* Deep single-engine body with bulged DSI intakes and the C-model's oversized long-span folding wings. */
  cstealth_n: {era:"e20", fac:"nato", role:"cstealth", designation:"Lockheed Martin F-35C", len:15.7, span:13.1, planform:"trap", sweep:33, taper:0.28, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"dsi", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.7, camo:"twotone"},
  /* Super Hornet planform carrying fat ALQ-218 pods on the wingtips instead of missile rails, with jammer pods under the belly. */
  ew_n: {era:"e20", fac:"nato", role:"ewair", designation:"EA-18G Growler", len:18.3, span:13.6, planform:"trap", sweep:27, taper:0.32, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.15, camo:"twotone"},
  /* Single chin intake under a one-piece bubble canopy, blended body, one fin and slab tails. */
  fighter_n: {era:"e20", fac:"nato", role:"fighter", designation:"F-16C Block 52", len:15, span:9.9, planform:"trap", sweep:40, taper:0.23, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"twotone"},
  /* Pure flying wing with a double-W sawtooth trailing edge, buried engines venting on top, and no vertical surfaces at all. */
  sbomber_n: {era:"e20", fac:"nato", role:"stealthbomber", designation:"B-2A Spirit", len:21, span:52.4, planform:"fwing", sweep:33, taper:0.25, dihedral:0, prop:"none", engines:4, engMount:"wing", intake:"dorsal", tail:"none", htail:"none", wingpos:"mid", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:1, camo:"black"},
  /* Standard F-16 outline; the only cue is the HARM targeting pod strapped to the right intake cheek. */
  sead_n: {era:"e20", fac:"nato", role:"sead", designation:"F-16CJ Block 50 SEAD", len:15, span:9.9, planform:"trap", sweep:40, taper:0.23, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"twotone"},
  /* Diamond wing with huge trapezoidal stabilators almost as big as the wing, plus outward-canted twin fins. */
  stealth_n: {era:"e20", fac:"nato", role:"stealthfighter", designation:"F-22A Raptor", len:18.9, span:13.6, planform:"trap", sweep:42, taper:0.17, dihedral:3, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.8, camo:"twotone"},
  /* Il-76 high wing with anhedral and a tall T-tail, carrying a rotodome above the rear fuselage. */
  awacs_p: {era:"e20", fac:"pact", role:"awacs", designation:"Beriev A-50U Mainstay", len:46.6, span:50.5, planform:"swept", sweep:25, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"ttail", htail:"high", wingpos:"high", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Near-straight shoulder wing ending in split-airbrake tip pods, engines faired flat along the fuselage sides. */
  bomber_p: {era:"e20", fac:"pact", role:"cas", designation:"Su-25SM3 Frogfoot", len:15.5, span:14.4, planform:"straight", sweep:20, taper:0.45, dihedral:-2, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"single", htail:"mid", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Flanker with small canard foreplanes on the LERX, folding wings, and a shortened tail stinger between the twin fins. */
  cfighter_p: {era:"e20", fac:"pact", role:"cfighter", designation:"Sukhoi Su-33", len:21.2, span:14.7, planform:"swept", sweep:42, taper:0.24, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:true, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Widely splayed engine nacelles with an air tunnel between them and enormous curved LERX running to the cockpit. */
  fighter_p: {era:"e20", fac:"pact", role:"fighter", designation:"MiG-29S Fulcrum-C", len:17.3, span:11.4, planform:"trap", sweep:42, taper:0.25, dihedral:-2, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  /* Huge all-white blended swing-wing with four engines paired in two boxes under the wing gloves. */
  sbomber_p: {era:"e20", fac:"pact", role:"stealthbomber", designation:"Tu-160M Blackjack", len:54.1, span:55.7, planform:"swing", sweep:20, taper:0.3, dihedral:0, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"single", htail:"mid", wingpos:"mid", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0.15, camo:"white"},
  /* Broad side-by-side two-seat cockpit and boxy square side intakes ahead of shoulder-mounted swing wings. */
  sead_p: {era:"e20", fac:"pact", role:"sead", designation:"Su-24M (Kh-31P)", len:24.5, span:17.6, planform:"swing", sweep:16, taper:0.35, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  /* Flanker-wide spacing between the engines with a flat tunnel between them, small canted fins, and movable LEVCONs on the wing roots. */
  stealth_p: {era:"e20", fac:"pact", role:"stealthfighter", designation:"Su-57 Felon", len:20.1, span:14.1, planform:"trap", sweep:48, taper:0.2, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.6, camo:"darkgrey"},
  /* Four-turboprop high-wing transport with a fixed flat disc radome sitting on a pylon over the wing. */
  awacs_c: {era:"e20", fac:"pla", role:"awacs", designation:"Shaanxi KJ-500 AEW&C", len:36.1, span:38, planform:"straight", sweep:5, taper:0.4, dihedral:2, prop:"turboprop", engines:4, engMount:"pod", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"airliner", canard:false, rotodome:true, fixedRadome:true, canoe:false, stealth:0, camo:"bluegrey"},
  /* Long tandem two-seat nose, shoulder-set swept wing with a dogtooth, and strongly drooped all-moving tailplanes under one tall fin. */
  bomber_c: {era:"e20", fac:"pla", role:"cas", designation:"JH-7A Flying Leopard", len:22.3, span:12.7, planform:"swept", sweep:45, taper:0.3, dihedral:-5, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Canard-equipped Flanker with folding outer wings and a stubby tail stinger — a Su-33 in PLAN blue-grey. */
  cfighter_c: {era:"e20", fac:"pla", role:"cfighter", designation:"Shenyang J-15", len:21.9, span:14.7, planform:"swept", sweep:42, taper:0.24, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:true, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* F-35-like faceted nose but with two engines and two nozzles side by side, canted fins and folding carrier wings. */
  cstealth_c: {era:"e20", fac:"pla", role:"cstealth", designation:"Shenyang J-35 (carrier)", len:17.3, span:11.5, planform:"trap", sweep:38, taper:0.25, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"dsi", tail:"twincant", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.7, camo:"darkgrey"},
  /* Two-seat Flanker with the nose IRST ball deleted and large jamming pods on both wingtips. */
  ew_c: {era:"e20", fac:"pla", role:"ewair", designation:"Shenyang J-16D", len:21.9, span:14.7, planform:"swept", sweep:42, taper:0.24, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"darkgrey"},
  /* Tailless delta with close-coupled canards and a bulged DSI chin intake under one very tall fin. */
  fighter_c: {era:"e20", fac:"pla", role:"fighter", designation:"J-10C Vigorous Dragon", len:15.5, span:9.8, planform:"delta", sweep:54, taper:0.17, dihedral:-3, prop:"none", engines:1, engMount:"fuselage", intake:"dsi", tail:"single", htail:"none", wingpos:"mid", fuselage:"slim", canard:true, rotodome:false, canoe:false, stealth:0.2, camo:"darkgrey"},
  /* Badger bomber with the engines buried in the wing roots bulging out of the fuselage sides, solid radar nose, refuelling probe and a belly recess for the big missile. */
  sbomber_c: {era:"e20", fac:"pla", role:"stealthbomber", designation:"Xian H-6N", len:34.8, span:33, planform:"swept", sweep:38, taper:0.3, dihedral:-3, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"mid", wingpos:"mid", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Standard two-seat Flanker outline with twin fins and a tail stinger, hauling long anti-radiation missiles under the wing gloves. */
  sead_c: {era:"e20", fac:"pla", role:"sead", designation:"Shenyang J-16 (YJ-91)", len:21.9, span:14.7, planform:"swept", sweep:42, taper:0.24, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"darkgrey"},
  /* Very long chined forebody with canards ahead of a cropped delta and only tiny all-moving canted fins at the back. */
  stealth_c: {era:"e20", fac:"pla", role:"stealthfighter", designation:"J-20A Mighty Dragon", len:21.2, span:13, planform:"cropdelta", sweep:48, taper:0.2, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"dsi", tail:"twincant", htail:"none", wingpos:"mid", fuselage:"wide", canard:true, rotodome:false, canoe:false, stealth:0.75, camo:"darkgrey"},
  /* Hawkeye's unmistakable four-fin tail and big pylon-mounted rotodome over a short high-wing turboprop body. */
  awacs_r: {era:"e20", fac:"roc", role:"awacs", designation:"Northrop E-2K Hawkeye 2000", len:17.6, span:24.6, planform:"straight", sweep:3, taper:0.45, dihedral:2, prop:"turboprop", engines:2, engMount:"pod", intake:"none", tail:"quad", htail:"mid", wingpos:"high", fuselage:"wide", canard:false, rotodome:true, canoe:false, stealth:0, camo:"seagrey"},
  /* Small F-16-sized airframe but with two Hornet-style cheek intakes under the LERX feeding twin engines behind a single fin. */
  bomber_r: {era:"e20", fac:"roc", role:"cas", designation:"F-CK-1C Ching-kuo", len:14.2, span:9, planform:"trap", sweep:34, taper:0.3, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.05, camo:"twotone"},
  /* Plan view identical to any F-16 — chin intake and one fin; only the thickened dorsal spine gives the V away. */
  fighter_r: {era:"e20", fac:"roc", role:"fighter", designation:"F-16V Block 70", len:15, span:9.9, planform:"trap", sweep:40, taper:0.23, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0.1, camo:"twotone"},
  /* Armoured two-seat Sturmovik with a wide straight low wing and the unmistakable long two-place greenhouse canopy over the wing. */
  kpa_e50_cas: {era:"e50", fac:"kpa", role:"cas", designation:"Il-10", len:11.1, span:13.4, planform:"straight", sweep:6, taper:0.45, dihedral:5, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* Very small inline-engined piston fighter: pointed spinner, cut-down rear decking with a teardrop canopy, and a short straight wing only a metre wider than the aircraft is long. */
  kpa_e50_fighter: {era:"e50", fac:"kpa", role:"fighter", designation:"Yak-9P", len:8.6, span:9.7, planform:"straight", sweep:5, taper:0.45, dihedral:5, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Dolphin-curved Constellation fuselage on four big radial nacelles with a multi-fin tail (really a triple fin) and an enormous APS-20 belly radome slung under the forward fuselage plus a dorsal height-finder fin. */
  nato_e50_awacs: {era:"e50", fac:"nato", role:"awacs", designation:"EC-121D Warning Star", len:35.4, span:38.5, planform:"straight", sweep:7, taper:0.35, dihedral:5, prop:"piston", engines:4, engMount:"pod", intake:"none", tail:"quad", htail:"low", wingpos:"low", fuselage:"airliner", canard:false, rotodome:false, canoe:true, stealth:0, camo:"white"},
  /* Huge four-blade paddle propeller on a stubby single-seat fuselage, with a very long straight wing spanning several metres more than the aircraft's length and studded with pylons. */
  nato_e50_cas: {era:"e50", fac:"nato", role:"cas", designation:"AD-4 Skyraider", len:11.8, span:15.2, planform:"straight", sweep:6, taper:0.4, dihedral:6, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Skyraider planform but visibly fattened: a deep, wide side-by-side cabin with a taller fin, and ECM pods hung under the long straight wing. */
  nato_e50_ewair: {era:"e50", fac:"nato", role:"ewair", designation:"AD-5Q Skyraider", len:12.2, span:15.2, planform:"straight", sweep:6, taper:0.4, dihedral:6, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Bare-metal swept fighter with an oval nose intake and a low-set slab tailplane far below the fin, distinguishing it from the fin-mounted tail of the MiG-17. */
  nato_e50_fighter: {era:"e50", fac:"nato", role:"fighter", designation:"F-86F Sabre", len:11.4, span:11.3, planform:"swept", sweep:35, taper:0.5, dihedral:3, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Late Sturmovik rebuild: the same two-seat greenhouse but on a longer fuselage and a new, wider straight wing with square-cut tips and almost no leading-edge sweep. */
  pact_e50_cas: {era:"e50", fac:"pact", role:"cas", designation:"Il-10M", len:11.9, span:14, planform:"straight", sweep:3, taper:0.55, dihedral:4, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Nose-intake tube with anhedral 45-degree swept wings and a tailplane perched partway up a broad swept fin, the wing noticeably shorter in span than the fuselage is long. */
  pact_e50_fighter: {era:"e50", fac:"pact", role:"fighter", designation:"MiG-17F Fresco-C", len:11.3, span:9.6, planform:"swept", sweep:45, taper:0.5, dihedral:-3, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"mid", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Long-nosed piston attacker with a broad straight low wing and a glasshouse canopy stretched back to a separate rear gunner's station. */
  pla_e50_cas: {era:"e50", fac:"pla", role:"cas", designation:"Il-10", len:11.1, span:13.4, planform:"straight", sweep:6, taper:0.45, dihedral:5, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* Barrel fuselage with a round nose intake and sharply 45-degree swept, slightly drooped wings carrying three tall boundary-layer fences per side. */
  pla_e50_fighter: {era:"e50", fac:"pla", role:"fighter", designation:"J-5 (MiG-17F)", len:11.3, span:9.6, planform:"swept", sweep:45, taper:0.5, dihedral:-3, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"mid", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Cigar fuselage with a nose intake and a dead-straight mid-wing that always ends in permanently fitted wingtip tanks. */
  roc_e50_cas: {era:"e50", fac:"roc", role:"cas", designation:"F-84G Thunderjet", len:11.7, span:11.1, planform:"straight", sweep:6, taper:0.5, dihedral:3.5, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"low", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Oval nose intake under a clear bubble canopy, 35-degree swept wing of near-equal span and length, and a low all-flying tailplane sitting well below the fin. */
  roc_e50_fighter: {era:"e50", fac:"roc", role:"fighter", designation:"F-86F-30 Sabre", len:11.4, span:11.3, planform:"swept", sweep:35, taper:0.5, dihedral:3, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Big fat cylinder of a fuselage with a wide circular nose intake and a very sharply swept wing that looks too small for it. */
  kpa_e60_cas: {era:"e60", fac:"kpa", role:"cas", designation:"Su-7BMK", len:16.8, span:8.9, planform:"swept", sweep:60, taper:0.3, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Small tailed delta whose circular nose intake carries a blunt shock cone, with a thick dorsal spine running from canopy to fin. */
  kpa_e60_fighter: {era:"e60", fac:"kpa", role:"fighter", designation:"MiG-21PFM", len:14.7, span:7.2, planform:"delta", sweep:57, taper:0.15, dihedral:-2, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Enormous 7-metre rotodome on struts over a straight high wing, with four small fins spread across one wide tailplane. */
  nato_e60_awacs: {era:"e60", fac:"nato", role:"awacs", designation:"E-2 Hawkeye", len:17.6, span:24.6, planform:"straight", sweep:4, taper:0.45, dihedral:3, prop:"turboprop", engines:2, engMount:"wing", intake:"none", tail:"quad", htail:"high", wingpos:"high", fuselage:"wide", canard:false, rotodome:true, canoe:false, stealth:0, camo:"seagrey"},
  /* Short humpbacked tub of a fuselage with a huge gaping chin intake under a stubby nose and a shoulder wing that folds well outboard. */
  nato_e60_cas: {era:"e60", fac:"nato", role:"cas", designation:"A-7 Corsair II", len:14.1, span:11.8, planform:"swept", sweep:35, taper:0.35, dihedral:-3, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Blunt round nose and a long four-seat greenhouse canopy, with a bulbous ECM football perched on top of the swept fin. */
  nato_e60_ewair: {era:"e60", fac:"nato", role:"ewair", designation:"EA-6B Prowler", len:18.2, span:16.2, planform:"swept", sweep:28, taper:0.3, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Dogtoothed outer wing panels cranked sharply upward while the one-piece tailplane droops steeply down — bent both ways at once. */
  nato_e60_fighter: {era:"e60", fac:"nato", role:"fighter", designation:"F-4 Phantom II", len:19.2, span:11.7, planform:"swept", sweep:45, taper:0.26, dihedral:12, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"anhedral", wingpos:"low", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Forward-swept wing-root intakes slashing into the leading edge of a very long coke-bottle fuselage under a big swept fin. */
  nato_e60_sead: {era:"e60", fac:"nato", role:"sead", designation:"F-105G Wild Weasel", len:19.6, span:10.6, planform:"swept", sweep:45, taper:0.3, dihedral:-3.5, prop:"none", engines:1, engMount:"fuselage", intake:"wingroot", tail:"single", htail:"slab", wingpos:"mid", fuselage:"area", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Airliner-sized swept-wing turboprop with four huge contra-prop nacelles and an 11-metre rotodome on a pylon behind the wing. */
  pact_e60_awacs: {era:"e60", fac:"pact", role:"awacs", designation:"Tu-126 Moss", len:55.2, span:51.2, planform:"swept", sweep:37, taper:0.3, dihedral:2, prop:"turboprop", engines:4, engMount:"wing", intake:"none", tail:"single", htail:"mid", wingpos:"low", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"silver"},
  /* Su-7 body with only the outer wing panels pivoting, so the leading edge kinks hard where the fixed 63-degree glove meets the swinging panel. */
  pact_e60_cas: {era:"e60", fac:"pact", role:"cas", designation:"Su-17 Fitter", len:18.8, span:13.7, planform:"swing", sweep:55, taper:0.3, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Tiny pure tailed delta with a pointed shock-cone nose intake and a fat spine swelling aft of the canopy into the fin root. */
  pact_e60_fighter: {era:"e60", fac:"pact", role:"fighter", designation:"MiG-21", len:14.7, span:7.2, planform:"delta", sweep:57, taper:0.15, dihedral:-2, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Same kinked swing-wing Fitter shape, but with one enormous finned Kh-28 anti-radar missile slung on the centreline under the belly. */
  pact_e60_sead: {era:"e60", fac:"pact", role:"sead", designation:"Su-17M (Kh-28)", len:18.8, span:13.7, planform:"swing", sweep:55, taper:0.3, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* MiG-19 wing and twin tailpipes but with a solid pointed radar nose and oval cheek intakes pushed back beside the cockpit. */
  pla_e60_cas: {era:"e60", fac:"pla", role:"cas", designation:"Q-5", len:15.7, span:9.7, planform:"swept", sweep:55, taper:0.35, dihedral:-3, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"area", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Stubby wasp-waisted area-ruled body with a plain round nose intake and two exhaust nozzles side by side under a single tall fin. */
  pla_e60_fighter: {era:"e60", fac:"pla", role:"fighter", designation:"J-6", len:12.6, span:9, planform:"swept", sweep:57, taper:0.4, dihedral:-4.5, prop:"none", engines:2, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"mid", fuselage:"area", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Flattened oval shark-mouth nose intake ahead of a hard 45-degree swept wing, with the slab tailplane set unusually low, well below the wing line. */
  roc_e60_cas: {era:"e60", fac:"roc", role:"cas", designation:"F-100 Super Sabre", len:14.4, span:11.2, planform:"swept", sweep:45, taper:0.3, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* A pencil fuselage with tiny razor-straight stub wings barely wider than the tailplane, which sits right on top of the fin. */
  roc_e60_fighter: {era:"e60", fac:"roc", role:"fighter", designation:"F-104G Starfighter", len:16.7, span:6.7, planform:"straight", sweep:18, taper:0.39, dihedral:-10, prop:"none", engines:1, engMount:"fuselage", intake:"cheek", tail:"ttail", htail:"high", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Thick near-straight high wing with long engine boxes clamped to the fuselage flanks and bulged airbrake pods hanging off the wingtips. */
  kpa_e80_cas: {era:"e80", fac:"kpa", role:"cas", designation:"Su-25 Frogfoot", len:15.5, span:14.4, planform:"straight", sweep:19, taper:0.45, dihedral:0, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"low", wingpos:"high", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* Shoulder-mounted swing wings pivoting out of large fixed gloves on a slab-sided single-engine body with square box intakes and one tall fin. */
  kpa_e80_fighter: {era:"e80", fac:"kpa", role:"fighter", designation:"MiG-23ML", len:16.7, span:14, planform:"swing", sweep:16, taper:0.4, dihedral:-3, prop:"none", engines:1, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Boeing 707 airliner with four underwing pods and a nine-metre rotodome disc floating on twin struts above the rear fuselage. */
  nato_e80_awacs: {era:"e80", fac:"nato", role:"awacs", designation:"E-3 Sentry", len:46.6, span:44.4, planform:"swept", sweep:35, taper:0.28, dihedral:7, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"single", htail:"low", wingpos:"low", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Dead-straight wing wider than the aircraft is long, two fat turbofan cans bolted high on the rear fuselage between twin fins on a rectangular tailplane. */
  nato_e80_cas: {era:"e80", fac:"nato", role:"cas", designation:"A-10 Thunderbolt II", len:16.3, span:17.5, planform:"straight", sweep:3, taper:0.5, dihedral:4, prop:"none", engines:2, engMount:"rearpod", intake:"dorsal", tail:"twinboom", htail:"mid", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* Side-by-side-cockpit swing-wing with a long jamming canoe under the belly and a bulbous football fairing capping the fin. */
  nato_e80_ewair: {era:"e80", fac:"nato", role:"ewair", designation:"EF-111A Raven", len:23.2, span:19.2, planform:"swing", sweep:16, taper:0.4, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:true, stealth:0, camo:"seagrey"},
  /* Broad flat-bottomed body as wide as it is deep, huge shoulder-mounted cropped swept wing and two widely separated fins over squared box intakes. */
  nato_e80_fighter: {era:"e80", fac:"nato", role:"fighter", designation:"F-15C Eagle", len:19.4, span:13.1, planform:"swept", sweep:45, taper:0.25, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twin", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* Dogtoothed wing whose outer panels crank sharply upward while the all-moving tailplane droops just as sharply down. */
  nato_e80_sead: {era:"e80", fac:"nato", role:"sead", designation:"F-4G Wild Weasel V", len:19.2, span:11.7, planform:"swept", sweep:45, taper:0.2, dihedral:12, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"anhedral", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* A single black faceted arrowhead: no curves anywhere, no tailplane, just a steeply swept diamond ending in a canted butterfly V-tail. */
  nato_e80_stealthfighter: {era:"e80", fac:"nato", role:"stealthfighter", designation:"F-117 Nighthawk", len:20.1, span:13.2, planform:"faceted", sweep:67, taper:0.15, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"dorsal", tail:"twincant", htail:"none", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:1, camo:"black"},
  /* Il-76 freighter shape: high shoulder wing with four slung pods, a tall T-tail, and a rotodome on struts over the rear fuselage. */
  pact_e80_awacs: {era:"e80", fac:"pact", role:"awacs", designation:"A-50 Mainstay", len:46.6, span:50.5, planform:"swept", sweep:25, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"ttail", htail:"high", wingpos:"high", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Thick near-straight high wing bristling with pylons, engine boxes strapped to the fuselage sides and split airbrake pods on the wingtips. */
  pact_e80_cas: {era:"e80", fac:"pact", role:"cas", designation:"Su-25 Frogfoot", len:15.5, span:14.4, planform:"straight", sweep:19, taper:0.45, dihedral:0, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"low", wingpos:"high", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Two widely spaced engine nacelles with a daylight tunnel between them, huge curved wing-root extensions sweeping into the nose and outward-canted twin fins. */
  pact_e80_fighter: {era:"e80", fac:"pact", role:"fighter", designation:"MiG-29", len:17.3, span:11.4, planform:"trap", sweep:42, taper:0.25, dihedral:-2, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Enormous rectangular slab-sided intakes running most of the fuselage length, twin fins and a thin shoulder-mounted cropped delta drooping at the tips. */
  pact_e80_sead: {era:"e80", fac:"pact", role:"sead", designation:"MiG-25BM", len:23.8, span:14, planform:"cropdelta", sweep:41, taper:0.3, dihedral:-5, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twin", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Vast white blended-body swing-wing bomber with four engines paired into two long nacelles under the fixed centre section. */
  pact_e80_stealthbomber: {era:"e80", fac:"pact", role:"stealthbomber", designation:"Tu-160 Blackjack", len:54.1, span:55.7, planform:"swing", sweep:20, taper:0.25, dihedral:0, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"single", htail:"mid", wingpos:"low", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0.15, camo:"white"},
  /* MiG-19 wings on a pointed solid nose with oval cheek intakes and a pinched area-ruled waist ahead of twin tailpipes. */
  pla_e80_cas: {era:"e80", fac:"pla", role:"cas", designation:"Q-5C", len:15.7, span:9.7, planform:"swept", sweep:52, taper:0.35, dihedral:-4, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"area", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Extremely long slender tube with a small cropped-delta wing set well back and rectangular cheek intakes flanking a solid radar nose. */
  pla_e80_fighter: {era:"e80", fac:"pla", role:"fighter", designation:"J-8II", len:21.6, span:9.3, planform:"cropdelta", sweep:60, taper:0.2, dihedral:-2, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* Small tandem two-seat trainer with a long stepped greenhouse canopy and a near-straight low wing that spans almost as much as the aircraft is long. */
  roc_e80_cas: {era:"e80", fac:"roc", role:"cas", designation:"AT-3 Tzu Chung", len:12.9, span:10.5, planform:"swept", sweep:20, taper:0.4, dihedral:2, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"low", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Tiny needle-nosed jet whose stubby low-set trapezoidal wings with root extensions barely out-span the fuselage length of the intakes beside the cockpit. */
  roc_e80_fighter: {era:"e80", fac:"roc", role:"fighter", designation:"F-5E Tiger II", len:14.4, span:8.1, planform:"trap", sweep:24, taper:0.2, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"wingroot", tail:"single", htail:"slab", wingpos:"low", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Nearly straight shoulder wing hung with ten pylons, engine nacelles clamped against the fuselage sides, and split airbrake pods stuck out on the wingtips. */
  kpa_e90_cas: {era:"e90", fac:"kpa", role:"cas", designation:"Su-25K Frogfoot-A", len:15.5, span:14.4, planform:"straight", sweep:20, taper:0.4, dihedral:-2, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Tiny tailed delta on a cigar fuselage with a circular nose intake and shock cone, and a broad swept fin filling the whole rear deck. */
  kpa_e90_fighter: {era:"e90", fac:"kpa", role:"fighter", designation:"MiG-21bis Fishbed-N", len:14.7, span:7.2, planform:"delta", sweep:57, taper:0.15, dihedral:-2, prop:"none", engines:1, engMount:"fuselage", intake:"nose", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* 707 airliner with four underwing pods and, instead of a saucer, a 12 m side-looking radar canoe slung under the forward fuselage. */
  nato_e90_awacs: {era:"e90", fac:"nato", role:"awacs", designation:"E-8C Joint STARS", len:46.6, span:44.4, planform:"swept", sweep:35, taper:0.3, dihedral:7, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"single", htail:"low", wingpos:"low", fuselage:"airliner", canard:false, rotodome:false, canoe:true, stealth:0, camo:"white"},
  /* Huge shoulder-mounted swept wing over a flat wide body, twin slab-sided box intakes, and two upright fins outboard of enormous slab stabilators. */
  nato_e90_cas: {era:"e90", fac:"nato", role:"cas", designation:"F-15E Strike Eagle", len:19.4, span:13.1, planform:"swept", sweep:45, taper:0.25, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"twin", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  /* Fat blunt-nosed body with a long four-seat greenhouse canopy and a very tall fin capped by a football-shaped ALQ-99 fintop pod. */
  nato_e90_ewair: {era:"e90", fac:"nato", role:"ewair", designation:"EA-6B Prowler", len:18.2, span:16.2, planform:"swept", sweep:27, taper:0.35, dihedral:1, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* Single chin intake and bubble canopy, with a taller broad-chord fin and small strakes each side of the nozzle. */
  nato_e90_fighter: {era:"e90", fac:"nato", role:"fighter", designation:"F-16C Block 50", len:15, span:9.4, planform:"trap", sweep:40, taper:0.23, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* Standard F-16 outline distinguished only by the HTS pod on the intake cheek and a HARM hanging from each inboard pylon. */
  nato_e90_sead: {era:"e90", fac:"nato", role:"sead", designation:"F-16CJ Block 50D", len:15, span:9.4, planform:"trap", sweep:40, taper:0.23, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* A 52 m pure flying wing with a double-W sawtooth trailing edge, buried engines breathing through two dorsal inlets, and no fin of any kind. */
  nato_e90_stealthbomber: {era:"e90", fac:"nato", role:"stealthbomber", designation:"B-2A Spirit", len:21, span:52.4, planform:"fwing", sweep:33, taper:0.2, dihedral:0, prop:"none", engines:4, engMount:"wing", intake:"dorsal", tail:"none", htail:"none", wingpos:"mid", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0.9, camo:"black"},
  /* Flat black faceted arrowhead: an extreme 67-degree diamond planform with gridded shoulder inlets, a butterfly V-tail, and no horizontal stabilisers at all. */
  nato_e90_stealthfighter: {era:"e90", fac:"nato", role:"stealthfighter", designation:"F-117A Nighthawk", len:20.1, span:13.2, planform:"faceted", sweep:67, taper:0.15, dihedral:0, prop:"none", engines:2, engMount:"wing", intake:"dorsal", tail:"twincant", htail:"none", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:1, camo:"black"},
  /* Il-76 freighter with a high anhedral wing, four underwing pods and a T-tail, carrying a 9 m rotodome on twin struts behind the wing. */
  pact_e90_awacs: {era:"e90", fac:"pact", role:"awacs", designation:"A-50 Mainstay", len:46.6, span:50.5, planform:"swept", sweep:25, taper:0.3, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"underwing", tail:"ttail", htail:"high", wingpos:"high", fuselage:"airliner", canard:false, rotodome:true, canoe:false, stealth:0, camo:"white"},
  /* Straight shoulder wing bristling with pylons, box nacelles hugging the fuselage flanks, and clamshell airbrake fairings projecting beyond the wingtips. */
  pact_e90_cas: {era:"e90", fac:"pact", role:"cas", designation:"Su-25 Frogfoot-A", len:15.5, span:14.4, planform:"straight", sweep:20, taper:0.4, dihedral:-2, prop:"none", engines:2, engMount:"wing", intake:"wingroot", tail:"single", htail:"low", wingpos:"shoulder", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"olive"},
  /* Flanker layout shrunk down: huge curved LERX running to the canopy, separate underslung intakes, and two outward-canted fins on slim tail booms with a fattened spine. */
  pact_e90_fighter: {era:"e90", fac:"pact", role:"fighter", designation:"MiG-29S Fulcrum-C", len:17.3, span:11.4, planform:"trap", sweep:42, taper:0.28, dihedral:-2, prop:"none", engines:2, engMount:"wing", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"darkgrey"},
  /* Broad side-by-side cockpit and square box intakes with swing wings pivoting off huge fixed gloves - the wide flat nose section is the giveaway from above. */
  pact_e90_sead: {era:"e90", fac:"pact", role:"sead", designation:"Su-24M Fencer-D", len:22.5, span:17.6, planform:"swing", sweep:16, taper:0.35, dihedral:-2, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Very long tandem-seat fuselage with a shoulder-mounted anhedral swept wing and one tall single fin - Phantom proportions but only one tail. */
  pla_e90_cas: {era:"e90", fac:"pla", role:"cas", designation:"JH-7 Flying Leopard", len:22.3, span:12.8, planform:"swept", sweep:45, taper:0.35, dihedral:-5, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"shoulder", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"seagrey"},
  /* Two widely spaced engine nacelles with a flat lifting tunnel between them, long ogival LERX and a stinger tail boom poking out past the nozzles. */
  pla_e90_fighter: {era:"e90", fac:"pla", role:"fighter", designation:"Su-27SK Flanker-B", len:21.9, span:14.7, planform:"swept", sweep:42, taper:0.24, dihedral:0, prop:"none", engines:2, engMount:"wing", intake:"underwing", tail:"twin", htail:"slab", wingpos:"mid", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"bluegrey"},
  /* Stubby high-wing turboprop carrying a 7.3 m rotodome on a pylon, with four vertical fins spread along one wide tailplane. */
  roc_e90_awacs: {era:"e90", fac:"roc", role:"awacs", designation:"E-2T Hawkeye", len:17.6, span:24.6, planform:"straight", sweep:4, taper:0.4, dihedral:2, prop:"turboprop", engines:2, engMount:"wing", intake:"none", tail:"quad", htail:"high", wingpos:"high", fuselage:"wide", canard:false, rotodome:true, canoe:false, stealth:0, camo:"seagrey"},
  /* F-16-like trapezoidal wing but noticeably shorter, with a pair of low cheek intakes under the LERX instead of a single chin scoop. */
  roc_e90_cas: {era:"e90", fac:"roc", role:"cas", designation:"F-CK-1A Ching-kuo", len:14.2, span:9, planform:"trap", sweep:34, taper:0.25, dihedral:0, prop:"none", engines:2, engMount:"fuselage", intake:"cheek", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
  /* Single chin intake under a frameless bubble canopy, with the wing blended into the body by broad LERX and wingtip missile rails. */
  roc_e90_fighter: {era:"e90", fac:"roc", role:"fighter", designation:"F-16A/B Block 20 MLU", len:15, span:9.4, planform:"trap", sweep:40, taper:0.23, dihedral:0, prop:"none", engines:1, engMount:"fuselage", intake:"chin", tail:"single", htail:"slab", wingpos:"mid", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"twotone"},
};
if (typeof Airframe3D !== "undefined" && Airframe3D.registerAll) Airframe3D.registerAll();
