/* ============ rotor_specs.js — real rotorcraft geometry, one row per machine ============
   Generated from a per-era spec pass with an adversarial historical audit.
   Rows marked kind:"wing" are aeroplanes (An-2, Po-2, C-46, Il-76) and are handed
   to the fixed-wing builder instead; everything else is built by rotor3d.js.
                                                                              */
var ROTORCRAFT = {
  /* Huge anhedral stub wings hung with pods, behind a double-bubble tandem canopy stepped like two separate blisters over a chin gun turret. */
  kpa_e00_gunship: {era:"e00", fac:"kpa", role:"gunship", designation:"Mil Mi-24D Hind-D", kind:"rotor", len:17.5, rotorD:17.3, config:"single", blades:5, tblades:3, body:"gunship", engine:"turbine", engines:2, gear:"sponson", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"green"},
  /* Single radial-engined biplane on a tailwheel, its two strut-and-wire braced wings spanning far wider than the stubby fabric fuselage is long. */
  kpa_e00_transport: {era:"e00", fac:"kpa", role:"transport", designation:"Antonov An-2 Colt (Y-5)", kind:"wing", len:12.4, span:18.2, planform:"biplane", sweep:0, taper:0.7, dihedral:0, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Grey Hawk with an under-nose radar radome, sonobuoy launcher tubes down the port flank and the tailwheel tucked forward for deck landings. */
  nato_e00_aswhelo: {era:"e00", fac:"nato", role:"aswhelo", designation:"Sikorsky MH-60R Seahawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"seagrey"},
  /* Longbow drum radar above the rotor head, slab-sided engine boxes on the shoulders and a chin turret under stepped tandem cockpits. */
  nato_e00_gunship: {era:"e00", fac:"nato", role:"gunship", designation:"Boeing AH-64E Apache Guardian", kind:"rotor", len:15.1, rotorD:14.6, config:"single", blades:4, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"olive"},
  /* Squat wide-track cabin under a low four-blade disc, with the tail rotor canted 20 degrees on a swept fin above a low stabilator. */
  nato_e00_transport: {era:"e00", fac:"nato", role:"transport", designation:"Sikorsky UH-60M Black Hawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"olive"},
  /* Spherical radar ball perched on the mast above the rotor, over sharply stepped flat-plate tandem canopies and a large chin cannon. */
  pact_e00_gunship: {era:"e00", fac:"pact", role:"gunship", designation:"Mil Mi-28N Night Hunter", kind:"rotor", len:17, rotorD:17.2, config:"single", blades:5, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"darkgrey"},
  /* Very wide five-blade disc over a deep glazed-nose cabin, twin intakes atop the roof, clamshell rear cargo doors and wheels half-buried in sponson fairings. */
  pact_e00_transport: {era:"e00", fac:"pact", role:"transport", designation:"Mil Mi-8AMTSh Terminator", kind:"rotor", len:18.2, rotorD:21.3, config:"single", blades:5, tblades:3, body:"utility", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Faceted triangular-section fuselage that tapers to a knife-edge underside, with upward-canted engine exhausts either side of the five-blade head. */
  pla_e00_gunship: {era:"e00", fac:"pla", role:"gunship", designation:"CAIC Z-10", kind:"rotor", len:14.2, rotorD:13, config:"single", blades:5, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"darkgrey"},
  /* Super Frelon boat hull with amphibious sponson floats along the flanks and a six-blade main rotor over a long upswept tail pylon. */
  pla_e00_transport: {era:"e00", fac:"pla", role:"transport", designation:"Changhe Z-8 (Mi-171 / Z-20 in service alongside)", kind:"rotor", len:23, rotorD:18.9, config:"single", blades:6, tblades:4, body:"heavy", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"olive"},
  /* Naval Hawk with the tailwheel moved far forward under the cabin, a belly search-radar radome and a folding tail pylon hinge line. */
  roc_e00_aswhelo: {era:"e00", fac:"roc", role:"aswhelo", designation:"Sikorsky S-70C(M)-2 Thunderhawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"seagrey"},
  /* Longbow drum radar riding above the four-blade head, with boxy shoulder-mounted engine nacelles and a chin turret slung under the stepped tandem cockpits. */
  roc_e00_gunship: {era:"e00", fac:"roc", role:"gunship", designation:"Boeing AH-64E Apache Guardian", kind:"rotor", len:15.1, rotorD:14.6, config:"single", blades:4, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"darkgrey"},
  /* Low flat-backed cabin with a swept-back tail pylon carrying a canted tail rotor and a broad tailplane stabilator low on the boom. */
  roc_e00_transport: {era:"e00", fac:"roc", role:"transport", designation:"Sikorsky UH-60M Black Hawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"green"},
  /* Enormous drooping anhedral weapon wings under a double-bubble stepped tandem canopy on a fat troop-carrying hull. */
  helo_k: {era:"e20", fac:"kpa", role:"gunship", designation:"Mi-24D Hind", kind:"rotor", len:17.5, rotorD:17.3, config:"single", blades:5, tblades:3, body:"gunship", engine:"turbine", engines:2, gear:"sponson", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"green"},
  /* The only biplane in the sky: two huge parallel-chord wings braced by interplane struts behind a blunt radial-engine cowling. */
  trans_k: {era:"e20", fac:"kpa", role:"transport", designation:"An-2 Colt", kind:"wing", len:12.4, span:18.2, planform:"biplane", sweep:0, taper:0.9, dihedral:1, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Black Hawk airframe carrying a flat chin radar radome, a bulged folding rotor pylon and the tailwheel moved far forward under a shortened boom. */
  asw_helo_n: {era:"e20", fac:"nato", role:"aswhelo", designation:"Sikorsky MH-60R Seahawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"seagrey"},
  /* Mast-mounted Longbow radar drum riding above the four-blade rotor, with an X-scissor tail rotor and long anhedral stub wings. */
  helo_n: {era:"e20", fac:"nato", role:"gunship", designation:"AH-64E Apache Guardian", kind:"rotor", len:15.1, rotorD:14.6, config:"single", blades:4, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"olive"},
  /* Low, flat-backed cabin with a canted tail rotor set high on a swept fin and a wide slab stabilator across the boom. */
  trans_n: {era:"e20", fac:"nato", role:"transport", designation:"UH-60M Black Hawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"olive"},
  /* Two stacked three-blade contra-rotating rotors and twin endplate fins with no tail rotor at all, on a stubby whale-shaped hull. */
  asw_helo_p: {era:"e20", fac:"pact", role:"aswhelo", designation:"Kamov Ka-27PL Helix", kind:"rotor", len:11.3, rotorD:15.9, config:"coaxial", blades:3, tblades:0, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"bluegrey"},
  /* Bulbous mast-top radar ball over a five-blade rotor with fat engine nacelles slung wide on the flanks and an X-form tail rotor. */
  helo_p: {era:"e20", fac:"pact", role:"gunship", designation:"Mi-28N Night Hunter", kind:"rotor", len:17, rotorD:17.2, config:"single", blades:5, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"twotone"},
  /* Huge five-blade rotor over a barrel fuselage with external fuel panniers on the flanks, clamshell rear cargo doors and a long upswept boom. */
  trans_p: {era:"e20", fac:"pact", role:"transport", designation:"Mi-8AMTSh Terminator", kind:"rotor", len:18.2, rotorD:21.3, config:"single", blades:5, tblades:3, body:"utility", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"twotone"},
  /* Small Dauphin airframe with a shrouded fenestron fan buried in the swept fin instead of an exposed tail rotor, plus a chin search radar. */
  asw_helo_c: {era:"e20", fac:"pla", role:"aswhelo", designation:"Harbin Z-9C", kind:"rotor", len:12.1, rotorD:11.9, config:"fenestron", blades:4, tblades:4, body:"compact", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"seagrey"},
  /* Sharply faceted triangular-section fuselage tapering to a knife-thin tandem canopy, with exhausts ducted upward and no mast sight. */
  helo_c: {era:"e20", fac:"pla", role:"gunship", designation:"Z-10ME Attack Helicopter", kind:"rotor", len:14.2, rotorD:12, config:"single", blades:5, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"darkgrey"},
  /* Black Hawk outline but with a five-blade main rotor and a deeper, taller cabin roof. */
  trans_c: {era:"e20", fac:"pla", role:"transport", designation:"Z-20 Transport Helicopter", kind:"rotor", len:15, rotorD:16, config:"single", blades:5, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"darkgrey"},
  /* Naval Seahawk with a chin radome, sonobuoy launcher panel down the port flank and a hinged folding tail on a short-boom Black Hawk hull. */
  asw_helo_r: {era:"e20", fac:"roc", role:"aswhelo", designation:"Sikorsky S-70C(M)-1/2 Thunderhawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"seagrey"},
  /* Longbow radar drum on the rotor mast above a stepped tandem cockpit, chin turret slung under the nose and an X-scissor tail rotor. */
  helo_r: {era:"e20", fac:"roc", role:"gunship", designation:"AH-64E Apache Guardian", kind:"rotor", len:15.1, rotorD:14.6, config:"single", blades:4, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"olive"},
  /* Squat four-blade utility hull with the tail rotor canted over on a swept fin and a broad stabilator low on the boom. */
  trans_r: {era:"e20", fac:"roc", role:"transport", designation:"UH-60M Black Hawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"olive"},
  /* Tiny fabric biplane: two equal constant-chord wings joined by N-struts and bracing wire, open cockpits and a fixed tailskid undercarriage, all painted matt black. */
  kpa_e50_transport: {era:"e50", fac:"kpa", role:"transport", designation:"Polikarpov Po-2 night harassment biplane", kind:"wing", len:8.2, span:11.4, planform:"biplane", sweep:0, taper:1, dihedral:2, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"slim", canard:false, rotodome:false, canoe:false, stealth:0, camo:"black"},
  /* A glazed goldfish-bowl cabin with the turbine bolted openly behind it and a completely uncovered welded-tube lattice tailboom, missile rails jutting from the cabin flanks. */
  nato_e50_gunship: {era:"e50", fac:"nato", role:"gunship", designation:"Sud Aviation SE.3130 Alouette II (AS.11)", kind:"rotor", len:9.7, rotorD:10.2, config:"single", blades:3, tblades:2, body:"compact", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Bulbous nose full of radial engine with clamshell cowling doors, the cockpit stacked in a stepped-up greenhouse on top of it, and a boom that kinks sharply downward at the tail. */
  nato_e50_transport: {era:"e50", fac:"nato", role:"transport", designation:"Sikorsky H-19D Chickasaw (S-55)", kind:"rotor", len:12.9, rotorD:16.2, config:"single", blades:3, tblades:2, body:"pod", engine:"piston", engines:1, gear:"wheel", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Fat piston-engined pod with a stepped cockpit sitting above the nose radial, four-leg fixed wheels, and a long slim tailboom trailing back from rear clamshell cargo doors. */
  pact_e50_transport: {era:"e50", fac:"pact", role:"transport", designation:"Mil Mi-4 Hound", kind:"rotor", len:16.8, rotorD:21, config:"single", blades:4, tblades:3, body:"pod", engine:"piston", engines:1, gear:"wheel", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"green"},
  /* Deep barrel fuselage with the big radial in the nose and the cockpit perched high above it, a ventral gunner's gondola under the belly and clamshell loading doors under the upswept tailboom. */
  pla_e50_transport: {era:"e50", fac:"pla", role:"transport", designation:"Mil Mi-4 Hound (PLA, Soviet-supplied)", kind:"rotor", len:16.8, rotorD:21, config:"single", blades:4, tblades:3, body:"pod", engine:"piston", engines:1, gear:"wheel", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Enormous figure-eight 'double bubble' fuselage that bulges deepest below the wing, slung between two of the largest radial engine nacelles ever fitted to a transport. */
  roc_e50_transport: {era:"e50", fac:"roc", role:"transport", designation:"Curtiss C-46D Commando", kind:"wing", len:23.3, span:32.9, planform:"straight", sweep:5, taper:0.35, dihedral:5, prop:"piston", engines:2, engMount:"wing", intake:"none", tail:"single", htail:"low", wingpos:"low", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"silver"},
  /* A single-engine radial biplane: two near-rectangular wings joined by I-struts and wires, huge fin and rudder, sitting nose-high on a fixed taildragger. */
  kpa_e60_transport: {era:"e60", fac:"kpa", role:"transport", designation:"An-2 Colt", kind:"wing", len:12.4, span:18.2, planform:"biplane", sweep:0, taper:0.65, dihedral:2, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"green"},
  /* Knife-thin one-metre-wide fuselage with stepped tandem canopy, chin turret and short stub wings, all hung under a Huey two-blade rotor on skids. */
  nato_e60_gunship: {era:"e60", fac:"nato", role:"gunship", designation:"AH-1G HueyCobra", kind:"rotor", len:13.5, rotorD:13.4, config:"single", blades:2, tblades:2, body:"gunship", engine:"turbine", engines:1, gear:"skid", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"olive"},
  /* Wide sliding-door cabin with a rounded greenhouse nose, skids, and the unmistakable slow two-blade rotor with stabiliser bar. */
  nato_e60_transport: {era:"e60", fac:"nato", role:"transport", designation:"UH-1 Huey", kind:"rotor", len:12.8, rotorD:14.6, config:"single", blades:2, tblades:2, body:"utility", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Huge drooping anhedral stub wings with end pylons and a stepped double-bubble tandem canopy on a long fuselage with retractable wheels in sponsons. */
  pact_e60_gunship: {era:"e60", fac:"pact", role:"gunship", designation:"Mi-24 Hind", kind:"rotor", len:17.5, rotorD:17.3, config:"single", blades:5, tblades:3, body:"gunship", engine:"turbine", engines:2, gear:"sponson", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"twotone"},
  /* Twin turbines faired flat across the cabin roof under a five-blade rotor, deeply glazed stepped nose, and a long slim tailboom to clamshell rear cargo doors. */
  pact_e60_transport: {era:"e60", fac:"pact", role:"transport", designation:"Mi-8 Hip", kind:"rotor", len:18.2, rotorD:21.3, config:"single", blades:5, tblades:3, body:"utility", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"green"},
  /* Barrel-shaped 1950s pod fuselage with the radial piston engine in the sloped nose and the glazed cockpit perched high above it, standing on four tall fixed wheeled legs. */
  pla_e60_transport: {era:"e60", fac:"pla", role:"transport", designation:"Z-5", kind:"rotor", len:16.8, rotorD:21, config:"single", blades:4, tblades:3, body:"pod", engine:"piston", engines:1, gear:"wheel", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Two-blade teetering rotor with its cross-wise stabiliser bar over a low slab-sided cabin on plain tubular skids. */
  roc_e60_transport: {era:"e60", fac:"roc", role:"transport", designation:"UH-1H Iroquois", kind:"rotor", len:12.8, rotorD:14.6, config:"single", blades:2, tblades:2, body:"utility", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"green"},
  /* Massive anhedral stub wings hung with rockets, stepped twin bubble canopies over a chin gun turret, and wheels folding into sponsons. */
  kpa_e80_gunship: {era:"e80", fac:"kpa", role:"gunship", designation:"Mi-24D Hind-D", kind:"rotor", len:17.5, rotorD:17.3, config:"single", blades:5, tblades:3, body:"gunship", engine:"turbine", engines:2, gear:"sponson", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"green"},
  /* A single-engine biplane: two braced wings with interplane struts and a huge radial cowling, flown matte black for night infiltration. */
  kpa_e80_transport: {era:"e80", fac:"kpa", role:"transport", designation:"An-2 Colt", kind:"wing", len:12.4, span:18.2, planform:"biplane", sweep:0, taper:0.8, dihedral:0, prop:"piston", engines:1, engMount:"nose", intake:"none", tail:"single", htail:"low", wingpos:"high", fuselage:"wide", canard:false, rotodome:false, canoe:false, stealth:0, camo:"black"},
  /* Slab-sided tandem gunship with boxy engine nacelles either side of the mast, tailwheel gear and the X-pattern offset tail rotor. */
  nato_e80_gunship: {era:"e80", fac:"nato", role:"gunship", designation:"AH-64A Apache", kind:"rotor", len:15.1, rotorD:14.6, config:"single", blades:4, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"olive"},
  /* Squat wide-stance utility hull with a low flat roofline, tailwheel far forward and a four-blade tail rotor canted 20 degrees off vertical. */
  nato_e80_transport: {era:"e80", fac:"nato", role:"transport", designation:"UH-60A Black Hawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"olive"},
  /* Stubby barrel fuselage with two stacked three-blade contra-rotating rotors, no tail rotor at all, twin endplate fins and a chin search radome. */
  pact_e80_aswhelo: {era:"e80", fac:"pact", role:"aswhelo", designation:"Ka-27PL Helix", kind:"rotor", len:11.3, rotorD:15.9, config:"coaxial", blades:3, tblades:0, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"radome", tandemseat:false, camo:"bluegrey"},
  /* Same whale-bodied stepped-canopy Hind but with a chin gun in a four-barrel turret and Shturm tubes on the drooping stub-wing tips. */
  pact_e80_gunship: {era:"e80", fac:"pact", role:"gunship", designation:"Mi-24V Hind-E", kind:"rotor", len:17.5, rotorD:17.3, config:"single", blades:5, tblades:3, body:"gunship", engine:"turbine", engines:2, gear:"sponson", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"twotone"},
  /* Enormous five-blade rotor over a long boxy cabin that tapers into clamshell rear cargo doors, glazed bug-eye nose and fixed tricycle wheels. */
  pact_e80_transport: {era:"e80", fac:"pact", role:"transport", designation:"Mi-8MT Hip-H", kind:"rotor", len:18.4, rotorD:21.3, config:"single", blades:5, tblades:3, body:"utility", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Tiny streamlined pod with a shrouded fenestron fan buried in the swept fin and four HOT tubes clipped to the cabin sides. */
  pla_e80_gunship: {era:"e80", fac:"pla", role:"gunship", designation:"SA 342L Gazelle", kind:"rotor", len:9.5, rotorD:10.5, config:"fenestron", blades:3, tblades:4, body:"compact", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"green"},
  /* Long low-slung Black Hawk hull with a canted four-blade tail rotor and swept horizontal stabilator, worn in a civil white-and-blue PLA scheme. */
  pla_e80_transport: {era:"e80", fac:"pla", role:"transport", designation:"S-70C-2", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"white"},
  /* Egg-shaped glazed teardrop body on skids with a thin tail boom and a five-blade rotor far wider than the fuselage, TOW tubes on the flanks. */
  roc_e80_gunship: {era:"e80", fac:"roc", role:"gunship", designation:"500MD/TOW Defender", kind:"rotor", len:7, rotorD:8.05, config:"single", blades:5, tblades:2, body:"compact", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* Single wide two-blade seesaw rotor with its stabilizer bar, greenhouse cabin on skids and the tall swept fin of the classic Huey. */
  roc_e80_transport: {era:"e80", fac:"roc", role:"transport", designation:"UH-1H Iroquois", kind:"rotor", len:12.8, rotorD:14.6, config:"single", blades:2, tblades:2, body:"utility", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"olive"},
  /* Double-bubble tandem canopies stepped up over a chin turret, with big drooping anhedral stub wings and wheels that retract into sponsons. */
  kpa_e90_gunship: {era:"e90", fac:"kpa", role:"gunship", designation:"Mi-24D Hind", kind:"rotor", len:17.5, rotorD:17.3, config:"single", blades:5, tblades:3, body:"gunship", engine:"turbine", engines:2, gear:"sponson", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"twotone"},
  /* A tall T-tail over a swept high wing slung with four turbofan pods, with a glazed navigator's gondola tucked under the chin radome. */
  kpa_e90_transport: {era:"e90", fac:"kpa", role:"transport", designation:"Il-76TD", kind:"wing", len:46.6, span:50.5, planform:"swept", sweep:27, taper:0.28, dihedral:-3, prop:"none", engines:4, engMount:"pod", intake:"none", tail:"ttail", htail:"high", wingpos:"high", fuselage:"heavy", canard:false, rotodome:false, canoe:false, stealth:0, camo:"white"},
  /* The drum-shaped Longbow radome balanced on the mast above the four-blade rotor - a disc floating over the disc. */
  nato_e90_gunship: {era:"e90", fac:"nato", role:"gunship", designation:"AH-64D Longbow Apache", kind:"rotor", len:15.1, rotorD:14.6, config:"single", blades:4, tblades:4, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:true, nose:"stepped", tandemseat:true, camo:"olive"},
  /* Long, low and flat-backed, with a wide low stabilator and a four-blade tail rotor canted over on a swept fin high above the tailwheel. */
  nato_e90_transport: {era:"e90", fac:"nato", role:"transport", designation:"UH-60L Black Hawk", kind:"rotor", len:15.3, rotorD:16.4, config:"single", blades:4, tblades:4, body:"utility", engine:"turbine", engines:2, gear:"wheel", stubs:false, mast:false, nose:"plain", tandemseat:false, camo:"green"},
  /* Two three-blade rotors stacked on one mast and absolutely no tail rotor, above a single-seat fighter-like nose and a tailplane with endplate fins. */
  pact_e90_gunship: {era:"e90", fac:"pact", role:"gunship", designation:"Ka-50 Black Shark", kind:"rotor", len:13.5, rotorD:14.5, config:"coaxial", blades:3, tblades:0, body:"gunship", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:false, nose:"plain", tandemseat:false, camo:"black"},
  /* Round porthole windows down a bus-sized cargo hull, twin intakes faired over the cockpit roof and weapon outriggers braced off the wheel sponsons. */
  pact_e90_transport: {era:"e90", fac:"pact", role:"transport", designation:"Mi-8 Hip", kind:"rotor", len:18.4, rotorD:21.3, config:"single", blades:5, tblades:3, body:"utility", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"twotone"},
  /* No tail rotor disc at all - the anti-torque fan is buried in a shrouded fenestron in the fin of a small round-nosed Dauphin carrying HJ-8 tubes on side pylons. */
  pla_e90_gunship: {era:"e90", fac:"pla", role:"gunship", designation:"Z-9W", kind:"rotor", len:12.1, rotorD:11.9, config:"fenestron", blades:4, tblades:4, body:"compact", engine:"turbine", engines:2, gear:"wheel", stubs:true, mast:false, nose:"plain", tandemseat:false, camo:"green"},
  /* A huge five-blade rotor over twin turbine humps faired onto the cabin roof, with a bus-like cargo box of round portholes ending in clamshell rear doors. */
  pla_e90_transport: {era:"e90", fac:"pla", role:"transport", designation:"Mi-17 / Mi-171", kind:"rotor", len:18.4, rotorD:21.3, config:"single", blades:5, tblades:3, body:"utility", engine:"turbine", engines:2, gear:"sponson", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
  /* A knife-thin fuselage no wider than the pilot's shoulders, stepped tandem canopy and a two-blade rotor that reads as one straight bar, all sitting on skids. */
  roc_e90_gunship: {era:"e90", fac:"roc", role:"gunship", designation:"AH-1W SuperCobra", kind:"rotor", len:13.9, rotorD:14.6, config:"single", blades:2, tblades:2, body:"gunship", engine:"turbine", engines:2, gear:"skid", stubs:true, mast:false, nose:"stepped", tandemseat:true, camo:"olive"},
  /* The two-blade rotor with its stabiliser bar crossed at ninety degrees above a slab-sided greenhouse cabin on plain skids - the classic Huey cross. */
  roc_e90_transport: {era:"e90", fac:"roc", role:"transport", designation:"UH-1H Iroquois", kind:"rotor", len:12.8, rotorD:14.6, config:"single", blades:2, tblades:2, body:"utility", engine:"turbine", engines:1, gear:"skid", stubs:false, mast:false, nose:"glass", tandemseat:false, camo:"olive"},
};

/* the rotorcraft build here; the aeroplanes join the fixed-wing table */
if (typeof Rotor3D !== "undefined" && Rotor3D.registerAll) Rotor3D.registerAll();
if (typeof AIRFRAMES !== "undefined" && typeof Airframe3D !== "undefined") {
  for (var _k in ROTORCRAFT) {
    if (ROTORCRAFT[_k].kind === "wing" && !AIRFRAMES[_k]) AIRFRAMES[_k] = ROTORCRAFT[_k];
  }
  Airframe3D.registerAll();
}
