/* ============ warship_specs.js -- real surface ship geometry, one row per hull ============
   Generated from a per-era naval spec pass with an adversarial historical audit.
   Consumed by warship3d.js, which turns each row into a silhouette. Fields are
   documented at the top of that file; len and beam are real metres and everything
   else is an enum the builder switches on. Submarines are deliberately absent --
   units3d_subs.js already owns every boat in the game.
                                                                              */
var WARSHIPS = {
  /* Blunt bow doors and ramp, a long flat open tank deck, and every bit of superstructure crammed right aft over the engine room. */
  lst: {era:"e50", fac:"both", role:"transport_sea", designation:"LST", len:100, beam:15.2, bow:"flush", super:"boxy", funnels:1, funnelStyle:"stack", mast:"pole", guns:2, gunCal:40, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Small blunt-bowed medium landing ship: bow ramp doors, one boxy wheelhouse right aft, twin 37 mm in open tubs. */
  lst_k: {era:"e50", fac:"kpa", role:"transport_sea", designation:"LSM", len:55, beam:7.5, bow:"flush", super:"boxy", funnels:1, funnelStyle:"stack", mast:"pole", guns:2, gunCal:37, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Open rectangular box of a hull with a bow ramp forward and a tiny pilothouse hard aft on the starboard quarter. */
  lst_r: {era:"e50", fac:"roc", role:"transport_sea", designation:"LCU", len:41.1, beam:8.8, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:20, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Chinese-built Riga: raised forecastle with a clear break, one single 100 mm forward and two more stepped aft, one thin raked stack amidships. */
  pla_e50_corvette: {era:"e50", fac:"pla", role:"corvette", designation:"PF", len:91.5, beam:10.2, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:3, gunCal:100, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Ex-Soviet Project 7 hull: two widely spaced raked pipe stacks and four single 130 mm in open shields, two forward and two aft. */
  pla_e50_destroyer: {era:"e50", fac:"pla", role:"destroyer", designation:"DD", len:112.5, beam:10.2, bow:"raised", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:4, gunCal:130, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Stubby ex-US patrol escort: one 3-inch/50 on the forecastle, short stack amidships, 40 mm tubs stepped around the after deckhouse. */
  roc_e50_corvette: {era:"e50", fac:"roc", role:"corvette", designation:"PCE", len:56.2, beam:10.1, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Ex-Japanese Kagero hull, flared bow and two raked stacks of unequal size, rearmed with American 5-inch/38 singles fore and aft. */
  roc_e50_destroyer: {era:"e50", fac:"roc", role:"destroyer", designation:"DD", len:118.5, beam:10.8, bow:"raised", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:3, gunCal:127, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Nineteen-metre stepped-hydroplane torpedo boat, one small open cockpit and two stern-facing deck troughs that drop the torpedoes over the transom. */
  kpa_e50_corvette: {era:"e50", fac:"kpa", role:"corvette", designation:"PT", len:19.1, beam:3.3, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:12.7, gunPos:"fore", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"green"},
  /* Flush-decked escort with one twin 3-inch/50 forward and one aft, a single upright stack, and the Weapon Alpha ASW rocket mount ahead of the bridge. */
  nato_e50_corvette: {era:"e50", fac:"nato", role:"corvette", designation:"DE", len:95.9, beam:11.2, bow:"flush", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:76, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Long flush deck, two well-separated stacks, and the giveaway gun split: only one 5-inch/54 forward with the other two superfiring aft. */
  nato_e50_destroyer: {era:"e50", fac:"nato", role:"destroyer", designation:"DD", len:127.4, beam:13.8, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:3, gunCal:127, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Three triple 8-inch turrets, two superfiring forward and one aft, with a heavy tower bridge and two upright stacks ringed by twin 5-inch mounts. */
  nato_e50_cruiser: {era:"e50", fac:"nato", role:"cruiser", designation:"CA", len:218.4, beam:23.3, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:3, gunCal:203, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"pad", radar:"dish", camo:"haze"},
  /* Full-width flight deck with a port-side angled landing area and four catapults, and one small island set well aft on the starboard deck edge with the uptakes faired into it. */
  nato_e50_carrier: {era:"e50", fac:"nato", role:"carrier", designation:"CVA", len:325, beam:39.6, bow:"carrier", super:"island", funnels:1, funnelStyle:"mack", mast:"lattice", guns:4, gunCal:127, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"hangar", radar:"dish", camo:"haze"},
  /* Small raised-forecastle escort with one 100 mm forward and two aft, a single raked stack, and RBU spigot mortars flanking the open bridge. */
  pact_e50_corvette: {era:"e50", fac:"pact", role:"corvette", designation:"SKR", len:91.5, beam:10.2, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:3, gunCal:100, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Flush deck with strong sheer and a knuckled raked stem, two raked stacks, and one enclosed twin 130 mm turret forward and one aft. */
  pact_e50_destroyer: {era:"e50", fac:"pact", role:"destroyer", designation:"DD", len:126.1, beam:12.8, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:130, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Four triple 6-inch turrets in two superfiring pairs fore and aft, two raked stacks, and heavy tripod masts bristling with rotating aerials. */
  pact_e50_cruiser: {era:"e50", fac:"pact", role:"cruiser", designation:"CL", len:210, beam:22, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:4, gunCal:152, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Riveted Riga-copy escort: three single 100 mm mounts, one aft-raked pipe stack, riveted plating seams, RBU mortars on the forecastle break. */
  pla_e60_corvette: {era:"e60", fac:"pla", role:"corvette", designation:"Type 065 Jiangnan-class frigate", len:90.9, beam:10.2, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:3, gunCal:100, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Kotlin-derived flush hull: twin 130 mm turrets fore and aft, two raked pipe stacks, and two triple SY-1 launcher boxes wedged between them. */
  pla_e60_destroyer: {era:"e60", fac:"pla", role:"destroyer", designation:"Type 051 Luda-class destroyer", len:132, beam:12.8, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:130, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Four slab SY-1 launcher boxes flanking a low humped deckhouse, twin 30 mm mounts fore and aft, stubby pole mast with a drum radar. */
  pla_e60_missileboat: {era:"e60", fac:"pla", role:"missileboat", designation:"Type 021 Huangfeng (Osa-I copy)", len:38.6, beam:7.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:30, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Tubby ex-US patrol escort: one open 3-inch mount on the forecastle, 40 mm tubs abreast a short thin stack, tripod mast, depth-charge racks aft. */
  roc_e60_corvette: {era:"e60", fac:"roc", role:"corvette", designation:"PCE-842-class patrol escort", len:56.2, beam:10.1, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Classic raised-forecastle destroyer: twin 5-inch/38 gunhouses fore and aft, two thin stacks, tripod lattice mast, ASROC box amidships and a DASH hangar. */
  roc_e60_destroyer: {era:"e60", fac:"roc", role:"destroyer", designation:"Gearing-class FRAM I (DD)", len:119, beam:12.4, bow:"raised", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"hangar", radar:"dish", camo:"haze"},
  /* Tiny hard-chine planing hull: a single 20 mm forward of a cabin-sized wheelhouse, two Hsiung Feng I boxes canted outboard on the open stern. */
  roc_e60_missileboat: {era:"e60", fac:"roc", role:"missileboat", designation:"Hai Ou class (Dvora derivative)", len:21.6, beam:5.5, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:20, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Narrow home-built escort: single 100 mm shields fore and aft, a thicket of twin 37/57 mm tubs, one squat stack, and Styx boxes abreast it. */
  kpa_e60_corvette: {era:"e60", fac:"kpa", role:"corvette", designation:"Najin-class frigate", len:100, beam:10, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:100, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Low missile boat almost buried under four hangar-like Styx launcher boxes, with small twin 30 mm turrets right forward and right aft. */
  kpa_e60_missileboat: {era:"e60", fac:"kpa", role:"missileboat", designation:"Project 205 Osa-I / Project 183R Komar", len:38.6, beam:7.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:30, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* One towering slab mack amidships dominates a high flush-decked hull; single 5-inch/54 forward with the ASROC box just ahead of the bridge. */
  nato_e60_corvette: {era:"e60", fac:"nato", role:"corvette", designation:"Knox-class frigate (FF-1052)", len:133.5, beam:14.3, bow:"flush", super:"boxy", funnels:1, funnelStyle:"mack", mast:"enclosed", guns:1, gunCal:127, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"hangar", radar:"dish", camo:"haze"},
  /* twin-arm mk 11 tartar launcher on the fantail */
  nato_e60_destroyer: {era:"e60", fac:"nato", role:"destroyer", designation:"Charles F. Adams-class DDG (DDG-2)", len:133.2, beam:14.3, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"rails", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Liner-long nuclear cruiser with no funnel at all: one enormous square blockhouse with flat SCANFAR billboards on all four faces, twin-arm Terrier rails forward and Talos aft. */
  nato_e60_cruiser: {era:"e60", fac:"nato", role:"cruiser", designation:"USS Long Beach (CGN-9)", len:219.8, beam:22.3, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"rails", ciws:0, helo:"pad", radar:"both", camo:"haze"},
  /* Uptake-free nuclear carrier whose small square island is a box of flat billboard array faces topped by a domed cone, angled deck to port. */
  nato_e60_carrier: {era:"e60", fac:"nato", role:"carrier", designation:"USS Enterprise (CVN-65)", len:317, beam:40.5, bow:"carrier", super:"island", funnels:0, funnelStyle:"none", mast:"pole", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:0, helo:"hangar", radar:"both", camo:"haze"},
  /* Sharp-sheered fast attack craft: 76 mm OTO turret forward, four Exocet canisters in two staggered pairs amidships, 40 mm on the stern. */
  nato_e60_missileboat: {era:"e60", fac:"nato", role:"missileboat", designation:"Type 148 Tiger (La Combattante IIa)", len:47, beam:7, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"lattice", guns:1, gunCal:76, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Stubby high-bowed ASW corvette: retractable SA-N-4 bin and twin RBU-6000 mortars crowding the forecastle, twin 57 mm right aft, one low capped funnel. */
  pact_e60_corvette: {era:"e60", fac:"pact", role:"corvette", designation:"Project 1124 Grisha-class", len:71.2, beam:9.8, bow:"raised", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:1, gunCal:57, gunPos:"aft", vls:0, launchers:"rails", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* All-gas-turbine hull identified by two widely spaced PAIRS of outward-canted uptakes, twin SA-N-1 arms and twin 76 mm fore and aft, two pyramid lattice masts. */
  pact_e60_destroyer: {era:"e60", fac:"pact", role:"destroyer", designation:"Project 61 Kashin-class", len:144, beam:15.8, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:76, gunPos:"foreaft", vls:0, launchers:"rails", ciws:0, helo:"pad", radar:"dish", camo:"darkgrey"},
  /* Two colossal lattice pagoda towers carrying Head Net dishes, with quadruple Shaddock tubes trained outboard fore and aft; twin 76 mm on the quarterdeck. */
  pact_e60_cruiser: {era:"e60", fac:"pact", role:"cruiser", designation:"Project 58 Kynda-class missile cruiser", len:142, beam:16, bow:"flush", super:"layered", funnels:2, funnelStyle:"mack", mast:"lattice", guns:2, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"pad", radar:"dish", camo:"darkgrey"},
  /* Steel-hulled Styx carrier: four coffin-shaped launcher boxes angled out over the sides, twin 30 mm fore and aft, squat mast with a Square Tie dish. */
  pact_e60_missileboat: {era:"e60", fac:"pact", role:"missileboat", designation:"Project 205 Osa-class", len:38.6, beam:7.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:30, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Half cruiser, half flat-top: a cruiser bow packed with twin SA-N-3 arms, RBU mortars and twin 57 mm, then one huge blockhouse and funnel, then a wide open helicopter deck aft. */
  pact_e60_carrier: {era:"e60", fac:"pact", role:"carrier", designation:"Project 1123 Moskva-class helicopter cruiser", len:189, beam:23, bow:"raised", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:2, gunCal:57, gunPos:"fore", vls:0, launchers:"rails", ciws:0, helo:"hangar", radar:"dish", camo:"darkgrey"},
  /* Squat raised-forecastle frigate: twin 100 mm turrets fore and aft, a single thin raked stack, and two quad C-801 box launchers set on the weather deck either side of it. */
  pla_e80_corvette: {era:"e80", fac:"pla", role:"corvette", designation:"Type 053H2 Jianghu-III", len:103.2, beam:10.8, bow:"raised", super:"boxy", funnels:1, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:100, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Kotlin-derived flush-decked gun destroyer: two twin 130 mm turrets, two tall raked stacks with lattice masts between them, and triple HY-2 Styx box launchers amidships. */
  pla_e80_destroyer: {era:"e80", fac:"pla", role:"destroyer", designation:"Type 051 Luda", len:132, beam:12.8, bow:"flush", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:130, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Asheville-hulled gunboat: 76 mm OTO on the forecastle, 40 mm on the fantail, turbine exhaust through the deckhouse and Hsiung Feng I boxes angled out amidships. */
  roc_e80_corvette: {era:"e80", fac:"roc", role:"corvette", designation:"Lung Chiang PGG-581", len:50.1, beam:7.3, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:76, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Gearing FRAM hull with the forecastle break intact: twin 5-inch forward, 76 mm aft, two stacks, and boxed SM-1 Standard bins wedged between them. */
  roc_e80_destroyer: {era:"e80", fac:"roc", role:"destroyer", designation:"Wu Chin III DDG (Gearing FRAM)", len:119, beam:12.4, bow:"raised", super:"layered", funnels:2, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"box", ciws:1, helo:"hangar", radar:"dish", camo:"haze"},
  /* Dvora-size hard-chine hull barely longer than its weapons: tiny pilothouse forward, 20 mm on the bow, two Hsiung Feng I canisters angled off the open stern. */
  roc_e80_missileboat: {era:"e80", fac:"roc", role:"missileboat", designation:"Hai Ou PBFG", len:21.6, beam:5.5, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:20, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Freakishly wide catamaran hull twice the beam its length suggests: single 100 mm forward, Styx bins amidships, and a clear helicopter deck across the twin sterns. */
  kpa_e80_corvette: {era:"e80", fac:"kpa", role:"corvette", designation:"Soho-class frigate", len:73.8, beam:15.5, bow:"flush", super:"boxy", funnels:1, funnelStyle:"stack", mast:"lattice", guns:1, gunCal:100, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"pad", radar:"dish", camo:"darkgrey"},
  /* Stretched local Osa: low boxy deckhouse with twin 30 mm fore and aft and four heavy Styx canisters filling the whole waist. */
  kpa_e80_missileboat: {era:"e80", fac:"kpa", role:"missileboat", designation:"Soju-class missile boat", len:41, beam:7.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:30, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Single-arm Mk 13 rail standing alone on a long bare forecastle, the 76 mm perched oddly amidships on the deckhouse roof, twin LAMPS hangars and Phalanx aft. */
  nato_e80_corvette: {era:"e80", fac:"nato", role:"corvette", designation:"Oliver Hazard Perry FFG-7", len:135.6, beam:13.7, bow:"flush", super:"boxy", funnels:1, funnelStyle:"mack", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"rails", ciws:1, helo:"hangar", radar:"dish", camo:"haze"},
  /* Very long flush deck with high freeboard and two widely spaced macks: 5-inch Mk 45 fore and aft, ASROC box launcher standing ahead of the bridge, big hangar aft. */
  nato_e80_destroyer: {era:"e80", fac:"nato", role:"destroyer", designation:"Spruance DD-963", len:171.7, beam:16.8, bow:"flush", super:"boxy", funnels:2, funnelStyle:"mack", mast:"pole", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"box", ciws:2, helo:"hangar", radar:"dish", camo:"haze"},
  /* spruance hull buried under slab deckhouses carrying four fixed octagonal spy-1a array faces, with a mk 26 twin-arm rail launcher on the forecastle and a second on the fantail. */
  nato_e80_cruiser: {era:"e80", fac:"nato", role:"cruiser", designation:"Ticonderoga CG-47", len:172.8, beam:16.8, bow:"flush", super:"boxy", funnels:2, funnelStyle:"mack", mast:"planar", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"rails", ciws:2, helo:"hangar", radar:"planar", camo:"haze"},
  /* Nuclear flight deck 76 m wide with a port-side angled landing area, four catapults and a small smokeless island set far aft to starboard under a lattice mast. */
  nato_e80_carrier: {era:"e80", fac:"nato", role:"carrier", designation:"Nimitz CVN-68", len:332.8, beam:40.8, bow:"carrier", super:"island", funnels:0, funnelStyle:"none", mast:"lattice", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:3, helo:"hangar", radar:"dish", camo:"haze"},
  /* Hydrofoil: stubby hull riding on retractable struts and foils, 76 mm OTO on the bow and eight Harpoon canisters stacked in two quad blocks right on the transom. */
  nato_e80_missileboat: {era:"e80", fac:"nato", role:"missileboat", designation:"Pegasus PHM-1", len:40, beam:8.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Very short and unusually wide, superstructure filling most of the hull under a huge spherical Band Stand radome, triple P-120 bins canted outboard on each beam, 76 mm right aft. */
  pact_e80_corvette: {era:"e80", fac:"pact", role:"corvette", designation:"Project 1234.1 Nanuchka", len:59.3, beam:11.8, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"none", radar:"dish", camo:"bluegrey"},
  /* AK-176 on the forecastle ahead of a low blocky bridge, two pairs of long Termit tubes stacked along each side of the waist, two AK-630 gatlings flanking the stern. */
  pact_e80_missileboat: {era:"e80", fac:"pact", role:"missileboat", designation:"Project 1241 Molniya (Tarantul)", len:56.1, beam:10.2, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:2, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Heavy sheered bow, twin 130 mm AK-130 turrets fore and aft, one broad capped stack, and quad Moskit tubes lying along each side under a Band Stand radome over the bridge. */
  pact_e80_destroyer: {era:"e80", fac:"pact", role:"destroyer", designation:"Project 956 Sovremenny", len:156.5, beam:17.3, bow:"flush", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:2, gunCal:130, gunPos:"foreaft", vls:0, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* Eight enormous twin P-500 tubes canted upward in pairs down both sides of the superstructure, twin 130 mm forward, and a big Top Dome radome over the S-300F drum hatches aft. */
  pact_e80_cruiser: {era:"e80", fac:"pact", role:"cruiser", designation:"Project 1164 Slava", len:186.4, beam:20.8, bow:"flush", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:1, gunCal:130, gunPos:"fore", vls:64, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* Small frigate: twin 100 mm on a raised forecastle, an octuple HQ-7 bin behind it, two triple YJ-8 canister racks amidships and a square helo hangar aft flanked by twin 37 mm. */
  pla_e90_corvette: {era:"e90", fac:"pla", role:"corvette", designation:"Type 053H3 Jiangwei II", len:112, beam:12.4, bow:"raised", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:1, gunCal:100, gunPos:"fore", vls:0, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* Two widely spaced square funnels over a flush deck, four quad YJ-83 boxes between them, and a broad twin helicopter hangar right aft - no VLS anywhere. */
  pla_e90_destroyer: {era:"e90", fac:"pla", role:"destroyer", designation:"Type 052 Luhu (DDG-112)", len:143, beam:15.9, bow:"flush", super:"boxy", funnels:2, funnelStyle:"capped", mast:"lattice", guns:1, gunCal:100, gunPos:"fore", vls:0, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* 60 m gunboat, nearly all hull: one 76 mm right on the stem, a single small boxy pilothouse with a pole mast, and Hsiung Feng II canisters squatting on the open fantail. */
  roc_e90_corvette: {era:"e90", fac:"roc", role:"corvette", designation:"pgg-603 ching chiang (class hull numbers pgg-603 to pgg-617)", len:61.4, beam:9.5, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"none", radar:"dish", camo:"haze"},
  /* Perry hull: bare flush forecastle with only a single-arm Mk 13 rail launcher, the 76 mm perched high on the deckhouse roof, plus two quad Hsiung Feng II boxes abaft the stack. */
  roc_e90_destroyer: {era:"e90", fac:"roc", role:"destroyer", designation:"FFG-1101 Cheng Kung", len:138.1, beam:13.7, bow:"flush", super:"boxy", funnels:1, funnelStyle:"capped", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"rails", ciws:1, helo:"hangar", radar:"dish", camo:"haze"},
  /* 21 m Dvora hull barely longer than its weapons: one tiny wheelhouse forward, a 20 mm on the bow, and two Hsiung Feng I boxes taking up the whole after deck. */
  roc_e90_missileboat: {era:"e90", fac:"roc", role:"missileboat", designation:"FABG Hai Ou", len:21.6, beam:5.4, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:20, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* 1950s-pattern gun frigate: single 100 mm fore and aft, stacked open bridge decks, one thin pipe funnel, lattice mast, RBU mortars on the forecastle and two Styx bins wedged in amidships. */
  kpa_e90_corvette: {era:"e90", fac:"kpa", role:"corvette", designation:"Najin-class frigate", len:102, beam:10.2, bow:"raised", super:"layered", funnels:1, funnelStyle:"stack", mast:"lattice", guns:2, gunCal:100, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Stretched Osa hull: four slab Styx launch bins, two per side, angled outboard around a low boxy bridge, with twin 30 mm mounts closing off bow and stern. */
  kpa_e90_missileboat: {era:"e90", fac:"kpa", role:"missileboat", designation:"Soju class", len:39, beam:7.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:30, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Long empty flush forecastle broken only by the single-arm Mk 13 rail, one tall pole mast, and a wide twin SH-60 hangar with the Phalanx on its roof. */
  nato_e90_corvette: {era:"e90", fac:"nato", role:"corvette", designation:"FFG-7 Oliver Hazard Perry", len:135.6, beam:13.7, bow:"flush", super:"boxy", funnels:1, funnelStyle:"capped", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"rails", ciws:1, helo:"hangar", radar:"dish", camo:"haze"},
  /* Very beamy clipper stem and one continuous sloped low-observable deckhouse carrying four fixed SPY-1D faces; two Mk 41 cell fields fore and aft, and a bare flight deck with no hangar. */
  nato_e90_destroyer: {era:"e90", fac:"nato", role:"destroyer", designation:"DDG-51 Arleigh Burke Flight I", len:153.9, beam:20.4, bow:"clipper", super:"faceted", funnels:2, funnelStyle:"capped", mast:"planar", guns:1, gunCal:127, gunPos:"fore", vls:90, launchers:"vls", ciws:2, helo:"pad", radar:"planar", camo:"haze"},
  /* Spruance hull with high slab sides: two upright blocky deckhouses carrying the SPY-1 octagons, twin 5-inch mounts at both ends, a big rotating SPS-49 aloft and Mk 41 hatches fore and aft. */
  nato_e90_cruiser: {era:"e90", fac:"nato", role:"cruiser", designation:"CG-52 Ticonderoga (VLS)", len:172.8, beam:16.8, bow:"flush", super:"boxy", funnels:2, funnelStyle:"capped", mast:"planar", guns:2, gunCal:127, gunPos:"foreaft", vls:122, launchers:"vls", ciws:2, helo:"hangar", radar:"both", camo:"haze"},
  /* Full-length angled deck with four catapults and four deck-edge lifts, and a small narrow starboard island with a lattice mast and no funnel at all - nuclear. */
  nato_e90_carrier: {era:"e90", fac:"nato", role:"carrier", designation:"CVN-68 Nimitz", len:332.8, beam:40.8, bow:"carrier", super:"island", funnels:0, funnelStyle:"none", mast:"lattice", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:3, helo:"hangar", radar:"dish", camo:"haze"},
  /* Chunky 71 m ASW hull with a retractable SA-N-4 twin-arm bin buried in the forecastle, twin RBU-6000 mortars ahead of the bridge and one low broad funnel - no helicopter. */
  pact_e90_corvette: {era:"e90", fac:"pact", role:"corvette", designation:"Project 1124M Grisha V", len:71.2, beam:10.2, bow:"raised", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"rails", ciws:1, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Twin 130 mm turrets at both ends, four fat Moskit tubes trained outboard along the break of the forecastle, a heavy lattice tower mast and a telescoping hangar over the amidships pad. */
  pact_e90_destroyer: {era:"e90", fac:"pact", role:"destroyer", designation:"Project 956 Sovremenny", len:156.4, beam:17.3, bow:"raised", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:2, gunCal:130, gunPos:"foreaft", vls:0, launchers:"box", ciws:4, helo:"pad", radar:"dish", camo:"bluegrey"},
  /* 252 m flush-decked nuclear battlecruiser: slab sides the whole length, a huge enclosed tower block amidships with one funnel, a forecastle paved in Granit and S-300F hatches, twin 130 mm right aft over a below-deck hangar. */
  pact_e90_cruiser: {era:"e90", fac:"pact", role:"cruiser", designation:"Project 1144.2 Pyotr Velikiy", len:252, beam:28.5, bow:"flush", super:"boxy", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:1, gunCal:130, gunPos:"fore", vls:96, launchers:"vls", ciws:4, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* Angled deck ending forward in a 12-degree ski jump instead of catapults, a tall heavy enclosed island with a big capped funnel and Sky Watch panels, and Granit hatches let into the deck forward. */
  pact_e90_carrier: {era:"e90", fac:"pact", role:"carrier", designation:"Project 1143.5 Admiral Kuznetsov", len:305, beam:35.4, bow:"carrier", super:"island", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:0, gunCal:0, gunPos:"none", vls:12, launchers:"vls", ciws:4, helo:"hangar", radar:"both", camo:"bluegrey"},
  /* STOBAR carrier: 14-degree ski-jump at the bow with no catapults, and a very long slab island carrying four Type 346 planar array faces plus a capped funnel; the Soviet Granit silos are plated over, and the only weapons are three Type 1130 gatlings and HQ-10 box launchers on sponsons. */
  pla_e00_carrier: {era:"e00", fac:"pla", role:"carrier", designation:"Type 001 Liaoning / Type 002 Shandong (Project 1143.6 derivative)", len:270, beam:75, bow:"carrier", super:"island", funnels:1, funnelStyle:"capped", mast:"planar", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:3, helo:"hangar", radar:"both", camo:"bluegrey"},
  /* Four Type 346 planar arrays let into the canted faces of a pyramidal bridge block, twin capped funnels well separated, and 64 universal VLS cells split 32 forward of the bridge and 32 abaft the second funnel. */
  pla_e00_destroyer: {era:"e00", fac:"pla", role:"destroyer", designation:"Type 052C Luyang II / Type 052D Luyang III", len:157, beam:17.2, bow:"clipper", super:"faceted", funnels:2, funnelStyle:"capped", mast:"planar", guns:1, gunCal:130, gunPos:"fore", vls:64, launchers:"vls", ciws:2, helo:"hangar", radar:"both", camo:"bluegrey"},
  /* Tiny 89 m stealth corvette: single 76 mm forward, an enclosed mast with one rotating Type 360 aerial, two twin YJ-83 box launchers amidships and an 8-cell HQ-10 box on the hangarless flight deck aft. */
  pla_e00_corvette: {era:"e00", fac:"pla", role:"corvette", designation:"Type 056 / 056A Jiangdao", len:89, beam:11.1, bow:"clipper", super:"faceted", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:2, helo:"pad", radar:"dish", camo:"bluegrey"},
  /* Wave-piercing catamaran: two slender hulls under a broad 12 m platform nearly a third of its own length, a single 30 mm gatling forward, a low faceted deckhouse and two flush four-round YJ-83 box launchers aft; waterjets, so no funnel. */
  pla_e00_missileboat: {era:"e00", fac:"pla", role:"missileboat", designation:"Type 022 Houbei", len:42.6, beam:12.2, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:30, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Stealth catamaran only 60 m long but 14 m across, with a 76 mm forward, Hsiung Feng II and III box launchers ranged along both sides of the wide after deck, and a Phalanx perched right at the transom. */
  roc_e00_corvette: {era:"e00", fac:"roc", role:"corvette", designation:"Tuo Chiang class PGG (Hsun Lien programme)", len:60.4, beam:14, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"pad", radar:"dish", camo:"darkgrey"},
  /* Spruance hull: long flush deck, two widely spaced macks, and - the giveaway - twin-arm Mk 26 rail launchers fore and aft instead of any VLS, with 5 in mounts at both ends and rotating SPS-48/SPS-49 aerials. */
  roc_e00_destroyer: {era:"e00", fac:"roc", role:"destroyer", designation:"Kee Lung class DDG (ex-USN Kidd class)", len:171.7, beam:16.8, bow:"flush", super:"boxy", funnels:2, funnelStyle:"mack", mast:"pole", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"rails", ciws:2, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* A 34 m boat almost entirely deckhouse: a single 20 mm mount forward, a small faceted bridge, and four Hsiung Feng II canisters in two stacked pairs filling the whole after deck. */
  roc_e00_missileboat: {era:"e00", fac:"roc", role:"missileboat", designation:"Kuang Hua VI class PCG", len:34.2, beam:7.6, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:20, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Crude angular KPN craft: chined slab sides meeting a low faceted deckhouse, a twin 30 mm turret forward, a second gatling aft, and two Kh-35-type box launchers canted outboard on the quarterdeck. */
  kpa_e00_missileboat: {era:"e00", fac:"kpa", role:"missileboat", designation:"Nongo class PGG", len:39, beam:6.5, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:30, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Semi-planing steel monohull with a hard chine knuckle running the length of a strongly flared bow, one faceted deckhouse block forward, a 57 mm on the stem, SeaRAM on the hangar roof, and waterjet exhausts in the transom so there is no funnel at all. */
  nato_e00_corvette: {era:"e00", fac:"nato", role:"corvette", designation:"LCS-1 Freedom class Littoral Combat Ship", len:115.3, beam:17.5, bow:"clipper", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:57, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"hangar", radar:"dish", camo:"haze"},
  /* Flight IIA is the Burke with twin helicopter hangars built out either side of the after 64-cell VLS, the Harpoon canisters deleted; four SPY-1D array faces on the sloped forward deckhouse, 32 cells forward of the bridge. */
  nato_e00_destroyer: {era:"e00", fac:"nato", role:"destroyer", designation:"DDG-51 Arleigh Burke class, Flight IIA", len:155.3, beam:20.1, bow:"clipper", super:"faceted", funnels:2, funnelStyle:"capped", mast:"planar", guns:1, gunCal:127, gunPos:"fore", vls:96, launchers:"vls", ciws:2, helo:"hangar", radar:"both", camo:"haze"},
  /* Flat 78 m flight deck with an angled landing area and four catapults; the island is small, boxy and set unusually far aft - about 70 percent of the way down the deck - with fixed planar array panels on its faces and no funnel. */
  nato_e00_carrier: {era:"e00", fac:"nato", role:"carrier", designation:"CVN-78 Gerald R. Ford class", len:317, beam:78, bow:"carrier", super:"island", funnels:0, funnelStyle:"none", mast:"planar", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:2, helo:"hangar", radar:"planar", camo:"haze"},
  /* One unbroken sloped composite superstructure runs from the 100 mm gun almost to the hangar, hiding two quadruple Uran box launchers behind side doors amidships; a spherical radome caps the enclosed mast and a helicopter hangar is built into the after end. */
  pact_e00_corvette: {era:"e00", fac:"pact", role:"corvette", designation:"Project 20380 Steregushchiy", len:104.5, beam:13, bow:"clipper", super:"faceted", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:1, gunCal:100, gunPos:"fore", vls:12, launchers:"box", ciws:2, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* Shallow-draught river-capable hull with almost no freeboard: A-190 100 mm forward, a single faceted blockhouse, and an 8-cell Kalibr UKSK let flush into the deck right behind it - a 74 m boat with a cruiser's missile. */
  pact_e00_missileboat: {era:"e00", fac:"pact", role:"missileboat", designation:"Project 21631 Buyan-M", len:74.1, beam:11, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:100, gunPos:"fore", vls:8, launchers:"vls", ciws:2, helo:"none", radar:"dish", camo:"bluegrey"},
  /* a pyramidal enclosed mainmast forward of the machinery spaces, with the two funnels abreast (side by side) well aft of both masts */
  pact_e00_cruiser: {era:"e00", fac:"pact", role:"cruiser", designation:"Project 1164 Atlant (Slava class)", len:186.4, beam:20.8, bow:"flush", super:"boxy", funnels:2, funnelStyle:"capped", mast:"enclosed", guns:1, gunCal:130, gunPos:"fore", vls:64, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"bluegrey"},
  /* Ski-jump bow with twelve flush P-700 Granit silo hatches let into the forward flight deck - the cruiser armament no other carrier has; long island with a big capped funnel, Sky Watch array panels on its sides, and Kashtan gun/missile turrets on sponsons all round. */
  pact_e00_carrier: {era:"e00", fac:"pact", role:"carrier", designation:"Project 1143.5 Admiral Kuznetsov", len:270, beam:72, bow:"carrier", super:"island", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:0, gunCal:0, gunPos:"none", vls:12, launchers:"vls", ciws:4, helo:"hangar", radar:"both", camo:"darkgrey"},
  /* Small planing aluminium hull, one low pilothouse set well forward, and remote 25 mm Mk 38 mounts on the forecastle and on the after deck. */
  boat_n: {era:"e20", fac:"nato", role:"patrol", designation:"PB Mk VI", len:25.9, beam:5.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:25, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Shallow-draught river gunboat: a big 100 mm A-190 turret on a very low forecastle, an angled stealth deckhouse, and a Grad-M rocket box abaft it. */
  boat_p: {era:"e20", fac:"pact", role:"patrol", designation:"Project 21630 Buyan", len:62, beam:9.6, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:100, gunPos:"fore", vls:0, launchers:"box", ciws:2, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Semi-planing waterjet monohull with a knuckled clipper stem, a 57 mm Mk 110 on the bow, one continuous sloped deckhouse and a cavernous stern boat ramp. */
  corvette_n: {era:"e20", fac:"nato", role:"corvette", designation:"LCS (Freedom class)", len:115.3, beam:17.5, bow:"clipper", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:57, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"hangar", radar:"dish", camo:"haze"},
  /* Lightly armed modular patrol corvette: one 76 mm AK-176MA forward, a tall sloped block amidships, and a helicopter hangar and pad taking up the whole after third. */
  corvette_p: {era:"e20", fac:"pact", role:"corvette", designation:"Project 22160 Vasily Bykov", len:94, beam:14.4, bow:"clipper", super:"faceted", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"none", ciws:0, helo:"hangar", radar:"dish", camo:"darkgrey"},
  /* Hydrofoil: retractable foils under a stubby planing hull, a 76 mm OTO turret on the bow and eight Harpoon canisters stacked in two blocks over the transom. */
  missileboat_n: {era:"e20", fac:"nato", role:"missileboat", designation:"PHM-1 Pegasus", len:40.5, beam:8.6, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Four huge Moskit tubes in two pairs angled outboard along the sides amidships, AK-176 forward, twin AK-630 gatlings aft and a ball radome over the bridge. */
  missileboat_p: {era:"e20", fac:"pact", role:"missileboat", designation:"Project 12411 Tarantul III", len:56.1, beam:10.2, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:2, helo:"none", radar:"dish", camo:"darkgrey"},
  /* Sloped low-observable deckhouse carrying four fixed SPY-1D octagon faces, two widely separated capped funnels, 96 Mk 41 cells split fore and aft, twin helo hangars. */
  destroyer_n: {era:"e20", fac:"nato", role:"destroyer", designation:"DDG-51 Arleigh Burke Flight IIA", len:155.3, beam:20.1, bow:"clipper", super:"faceted", funnels:2, funnelStyle:"capped", mast:"planar", guns:1, gunCal:127, gunPos:"fore", vls:96, launchers:"vls", ciws:1, helo:"hangar", radar:"both", camo:"haze"},
  /* Twin 130 mm AK-130 turrets fore and aft, quad Moskit tubes angled outboard on both sides of the bridge, single-arm SA-N-7 rails, and a telescoping hangar under the after mack. */
  destroyer_p: {era:"e20", fac:"pact", role:"destroyer", designation:"Project 956 Sovremenny", len:156.4, beam:17.3, bow:"flush", super:"boxy", funnels:1, funnelStyle:"mack", mast:"lattice", guns:2, gunCal:130, gunPos:"foreaft", vls:0, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"darkgrey"},
  /* Spruance hull under two upright slab deckhouses, one SPY-1 array pair facing forward and one aft, 5-inch mounts and a 61-cell Mk 41 magazine at each end. */
  cruiser_n: {era:"e20", fac:"nato", role:"cruiser", designation:"CG-47 Ticonderoga", len:172.8, beam:16.8, bow:"clipper", super:"boxy", funnels:2, funnelStyle:"capped", mast:"planar", guns:2, gunCal:127, gunPos:"foreaft", vls:122, launchers:"vls", ciws:2, helo:"hangar", radar:"both", camo:"haze"},
  /* Eight pairs of enormous Bazalt tubes ranked up both sides from bridge to funnel, a twin 130 mm forward, S-300F revolver hatches aft and a big lattice mainmast. */
  cruiser_p: {era:"e20", fac:"pact", role:"cruiser", designation:"Project 1164 Atlant (Slava)", len:186.4, beam:20.8, bow:"flush", super:"boxy", funnels:1, funnelStyle:"capped", mast:"lattice", guns:1, gunCal:130, gunPos:"fore", vls:64, launchers:"box", ciws:4, helo:"hangar", radar:"dish", camo:"darkgrey"},
  /* Full flight deck with an angled landing area, four catapults, a deck-edge lift each side forward of and abaft a small smokeless island set well aft to starboard. */
  carrier_n: {era:"e20", fac:"nato", role:"carrier", designation:"CVN-68 Nimitz", len:317, beam:40.8, bow:"carrier", super:"island", funnels:0, funnelStyle:"none", mast:"pole", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:3, helo:"hangar", radar:"both", camo:"haze"},
  /* No catapults: the bow rises into a 12-degree ski-jump, twelve Granit silo hatches are let into the forward deck, and the tall island carries a real funnel and lattice masts. */
  carrier_p: {era:"e20", fac:"pact", role:"carrier", designation:"Project 11435 Kuznetsov", len:270, beam:35.4, bow:"carrier", super:"island", funnels:1, funnelStyle:"capped", mast:"lattice", guns:0, gunCal:0, gunPos:"none", vls:12, launchers:"vls", ciws:4, helo:"hangar", radar:"both", camo:"darkgrey"},
  /* Wave-piercing catamaran - two slender hulls under a wide faceted bridge box, beam almost a third of its length, with a six-barrel 30 mm mount on the bow. */
  boat_c: {era:"e20", fac:"pla", role:"patrol", designation:"Type 022 Houbei", len:42.6, beam:12.2, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:30, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Small tumblehome-sided stealth corvette: 76 mm forward, two twin YJ-83 boxes amidships, an HQ-10 launcher on the after deckhouse and a bare helipad with no hangar. */
  corvette_c: {era:"e20", fac:"pla", role:"corvette", designation:"Type 056A Jiangdao", len:89, beam:11.1, bow:"clipper", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"pad", radar:"dish", camo:"bluegrey"},
  /* The catamaran in full missile fit: eight YJ-83 canisters in two flush quad boxes filling the wide flat afterdeck between the twin hulls. */
  missileboat_c: {era:"e20", fac:"pla", role:"missileboat", designation:"Type 022 Houbei (YJ-83)", len:42.6, beam:12.2, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:30, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"bluegrey"},
  /* Clipper stem, single 130 mm turret, four flat Type 346A array faces set high on a sloped bridge tower, 64 universal cells in a 32/32 split, twin capped funnels. */
  destroyer_c: {era:"e20", fac:"pla", role:"destroyer", designation:"Type 052D Luyang III", len:157, beam:17.2, bow:"clipper", super:"faceted", funnels:2, funnelStyle:"capped", mast:"planar", guns:1, gunCal:130, gunPos:"fore", vls:64, launchers:"vls", ciws:2, helo:"hangar", radar:"both", camo:"bluegrey"},
  /* Flush enclosed bow with no breakwater, one continuous sloped slab from stem to hangar, an integrated pyramid mast, and 112 cells in blocks of 64 and 48. */
  cruiser_c: {era:"e20", fac:"pla", role:"cruiser", designation:"Type 055 Renhai", len:180, beam:20, bow:"clipper", super:"faceted", funnels:2, funnelStyle:"capped", mast:"planar", guns:1, gunCal:130, gunPos:"fore", vls:112, launchers:"vls", ciws:1, helo:"hangar", radar:"both", camo:"bluegrey"},
  /* Flat deck, no ski-jump: three electromagnetic catapult tracks, two deck-edge lifts to starboard, and a short compact island well aft carrying Type 346B panels. */
  carrier_c: {era:"e20", fac:"pla", role:"carrier", designation:"Type 003 Fujian", len:316, beam:39, bow:"carrier", super:"island", funnels:1, funnelStyle:"capped", mast:"enclosed", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"box", ciws:3, helo:"hangar", radar:"planar", camo:"bluegrey"},
  /* Merchant-form auxiliary: raised forecastle, a long low cargo deck carrying four kingpost replenishment rigs, and the whole blocky bridge and funnel right aft. */
  oiler: {era:"e20", fac:"both", role:"oiler", designation:"T-AO Henry J. Kaiser", len:206.5, beam:29.7, bow:"raised", super:"boxy", funnels:1, funnelStyle:"capped", mast:"pole", guns:0, gunCal:0, gunPos:"none", vls:0, launchers:"none", ciws:0, helo:"pad", radar:"dish", camo:"haze"},
  /* a twin 23 mm (zu-23) tub on the bow with a twin 14.5 mm mg aft */
  boat_k: {era:"e20", fac:"kpa", role:"patrol", designation:"Chaho class", len:27.7, beam:6.1, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:23, gunPos:"fore", vls:0, launchers:"rails", ciws:0, helo:"none", radar:"dish", camo:"green"},
  /* Crude P-6 derived patrol craft with a small stacked open-bridge deckhouse amidships and manually worked 37 mm mounts fore and aft. */
  corvette_k: {era:"e20", fac:"kpa", role:"corvette", designation:"Nampo class", len:27.7, beam:6.7, bow:"flush", super:"layered", funnels:0, funnelStyle:"none", mast:"pole", guns:2, gunCal:14.5, gunPos:"foreaft", vls:0, launchers:"none", ciws:0, helo:"none", radar:"dish", camo:"green"},
  /* Enlarged Osa: four slab-sided Styx box launchers, two each side angled outboard, with twin 30 mm turrets fore and aft and a lattice mast carrying a Square Tie aerial. */
  missileboat_k: {era:"e20", fac:"kpa", role:"missileboat", designation:"Soju class", len:40.8, beam:7.8, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"lattice", guns:2, gunCal:30, gunPos:"foreaft", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"green"},
  /* a single-barrel 20 mm t-75 cannon forward */
  boat_r: {era:"e20", fac:"roc", role:"patrol", designation:"Kuang Hua VI (KH-6)", len:34.2, beam:7.6, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:20, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Wave-piercing catamaran corvette, very broad for its length, 76 mm on the centreline bow deck with Hsiung Feng canisters angled outboard on each wing deck. */
  corvette_r: {era:"e20", fac:"roc", role:"corvette", designation:"Tuo Chiang class", len:60.4, beam:14, bow:"flush", super:"faceted", funnels:0, funnelStyle:"none", mast:"enclosed", guns:1, gunCal:76, gunPos:"fore", vls:0, launchers:"box", ciws:1, helo:"pad", radar:"dish", camo:"haze"},
  /* Dvora-sized hull barely longer than its missiles: a tiny wheelhouse forward and a single pair of Hsiung Feng I boxes trained aft over the transom. */
  missileboat_r: {era:"e20", fac:"roc", role:"missileboat", designation:"Hai Ou class", len:21.6, beam:5.5, bow:"flush", super:"boxy", funnels:0, funnelStyle:"none", mast:"pole", guns:1, gunCal:20, gunPos:"fore", vls:0, launchers:"box", ciws:0, helo:"none", radar:"dish", camo:"haze"},
  /* Spruance hull but no VLS and no array faces: twin-arm Mk 26 rail launchers and 5-inch mounts fore and aft, big rotating SPS-48/49 aerials on lattice masts between two stacks. */
  destroyer_r: {era:"e20", fac:"roc", role:"destroyer", designation:"Kee Lung (ex-Kidd DDG-993)", len:171.6, beam:16.8, bow:"clipper", super:"boxy", funnels:2, funnelStyle:"capped", mast:"lattice", guns:2, gunCal:127, gunPos:"foreaft", vls:0, launchers:"rails", ciws:2, helo:"hangar", radar:"dish", camo:"haze"},
};
if (typeof Warship3D !== "undefined" && Warship3D.registerAll) Warship3D.registerAll();
