/* ================= nato_e00_stealthfighter.js  -  HERO MODEL =================
   F-35A Lightning II.  Hand-built reference airframe for era e00 aircraft:
   the rest of the e00 roster is generated by air3d_era.js and will be tuned
   to match the look established here.

   Model space follows the house contract and models3d.js:
       +X nose / front,  +Y left,  +Z up,  real metres.
   render3d.js applies rotation.x = -PI/2 and renormalises by measured length,
   so what survives to the screen is the PROPORTION.

   Why this shape and not "generic modern jet":
     - ONE engine.  A single round nozzle on the centreline, not a pair.
     - A chunky mid body: the F-35 is deep because the weapons bays are inside
       it.  The belly carries two long bay bulges the width of an AMRAAM.
     - A trapezoidal wing with a plain straight leading edge.  There is NO
       leading-edge root extension spike - that is the teen-series look
       (F-16/F-18) and putting one here would date the model twenty years.
     - Canted twin fins on short aft booms either side of the nozzle.
     - Diverterless supersonic intakes: a fixed compression BUMP moulded into
       the fuselage side ahead of a forward-raked cowl lip.  No splitter plate,
       no boundary-layer gap.  This is the single most identifiable feature of
       the aeroplane after the fin cant.
     - A faceted chined forebody: a hard horizontal edge runs from the radome
       back along the fuselage side and dies into the wing leading edge.

   Colour comes from the PAINT table at the top of js/air3d_era.js: this unit
   is spec'd camo "twotone", 0x768086, modern US grey-on-grey.  Roughness and
   metalness follow the house SKIN tier rather than the parametric values.

   Three material tiers only: SKIN (textured), METAL, GLASS.
============================================================================ */
if (typeof UNIT_MODELS === "undefined") { var UNIT_MODELS = {}; }

var HeroF35A = (function () {
  "use strict";

  var D2R = Math.PI / 180;

  /* ---- palette: js/air3d_era.js PAINT.twotone --------------------------- */
  var C_SKIN = 0x768086;      /* modern US grey-on-grey                     */
  var C_TOP = "#6b757c";      /* upper tactical grey                        */
  var C_LOW = "#8b959c";      /* lighter underside                          */
  var C_RAM = "#5c666d";      /* darker radar-absorbent panels              */
  var C_TRIM = "#98a2a8";     /* lighter LO trim panels                     */

  /* ======================================================================
     GEOMETRY HELPERS
     ====================================================================== */

  function sgnpow(v, e) { return (v < 0 ? -1 : 1) * Math.pow(Math.abs(v), e); }

  /* ---- generic skinner ---------------------------------------------------
     rings: array of equal-length arrays of [x,y,z].  Consecutive rings are
     bridged with quads.  skip lists ring-edge indices that must NOT produce a
     quad; that is how a crease is made - the two vertices either side of a
     hard edge are coincident, the quad between them is dropped, and each
     facet keeps its own normal instead of being averaged into a soft roll.
     Which is the whole point of a faceted stealth airframe.               */
  function skin(THREE, rings, skip, capA, capB) {
    var nr = rings.length, N = rings[0].length;
    var pos = [], uv = [], idx = [];
    var i, j, p, sk = {};
    if (skip) for (i = 0; i < skip.length; i++) sk[skip[i]] = 1;
    for (i = 0; i < nr; i++) {
      for (j = 0; j <= N; j++) {
        p = rings[i][j % N];
        pos.push(p[0], p[1], p[2]);
        uv.push(i / (nr - 1), j / N);
      }
    }
    var ring = N + 1;
    for (i = 0; i < nr - 1; i++) {
      for (j = 0; j < N; j++) {
        if (sk[j]) continue;
        var a = i * ring + j, b = a + 1, c = a + ring, d = c + 1;
        idx.push(a, c, b, b, c, d);
      }
    }
    if (capA) capFan(pos, uv, idx, rings[0], 0, sk);
    if (capB) capFan(pos, uv, idx, rings[nr - 1], 1, sk);
    var g = new THREE.BufferGeometry();
    g.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
    g.setAttribute("uv", new THREE.Float32BufferAttribute(uv, 2));
    g.setIndex(idx);
    g.computeVertexNormals();
    return g;
  }

  function capFan(pos, uv, idx, r, u, sk) {
    var N = r.length, cx = 0, cy = 0, cz = 0, i;
    for (i = 0; i < N; i++) { cx += r[i][0]; cy += r[i][1]; cz += r[i][2]; }
    var base = pos.length / 3;
    pos.push(cx / N, cy / N, cz / N); uv.push(u, 0.5);
    for (i = 0; i < N; i++) { pos.push(r[i][0], r[i][1], r[i][2]); uv.push(u, i / N); }
    for (i = 0; i < N; i++) {
      if (sk[i]) continue;
      var a = base + 1 + i, b = base + 1 + ((i + 1) % N);
      if (u === 0) idx.push(base, b, a); else idx.push(base, a, b);
    }
  }

  /* ---- Catmull-Rom resample of a station table --------------------------
     The station table below is written coarsely so it stays readable; this
     smooths it out lengthwise so the fuselage does not read as a stack of
     cones.                                                                */
  function cr1(p0, p1, p2, p3, t) {
    var t2 = t * t, t3 = t2 * t;
    return 0.5 * ((2 * p1) + (-p0 + p2) * t
      + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2
      + (-p0 + 3 * p1 - 3 * p2 + p3) * t3);
  }
  function resample(tab, n) {
    var m = tab.length, cols = tab[0].length, out = [], i, c;
    for (i = 0; i < n; i++) {
      var u = i / (n - 1) * (m - 1);
      var k = Math.min(m - 2, Math.floor(u));
      var t = u - k, row = [];
      for (c = 0; c < cols; c++) {
        row.push(cr1(tab[Math.max(0, k - 1)][c], tab[k][c],
                     tab[k + 1][c], tab[Math.min(m - 1, k + 2)][c], t));
      }
      out.push(row);
    }
    return out;
  }

  /* ---- chined fuselage section ------------------------------------------
     24 points around.  Indices 0/23 and 12/13 are coincident pairs at the
     port and starboard CHINE, and 16/17, 19/20 at the belly corners; the
     quads across those pairs are skipped so the chine stays a knife edge
     while the upper deck and the lower side stay smoothly rolled.
     s = { x, w, zc, zt, wt, cr, zb, wb }
       w  half width AT the chine        zc  chine height
       zt top-deck shoulder height       wt  top-deck shoulder half width
       cr crown above the shoulder       zb  belly height   wb belly half width */
  var CHINE_SKIP = [12, 16, 19, 23];
  function chineRing(s) {
    var w = s[1], zc = s[2], zt = s[3], wt = s[4], cr = s[5], zb = s[6], wb = s[7];
    var dt = zt - zc, db = zc - zb, x = s[0];
    /* the side above the chine and the side below it are FLAT facets, not
       rolls: interpolate straight from the chine corner to the shoulder and
       from the chine corner to the belly corner.  Rolling them - which is
       what a generic lofted fuselage does - turns the forebody into an egg
       and throws away the one thing this aeroplane is famous for. */
    var u1 = 0.30, u2 = 0.58, u3 = 0.82;   /* up   the side facet   */
    var d1 = 0.36, d2 = 0.70;              /* down the side facet   */
    var a1 = w + (wt - w) * u1, a2 = w + (wt - w) * u2, a3 = w + (wt - w) * u3;
    var b1 = w + (wb - w) * d1, b2 = w + (wb - w) * d2;
    return [
      [x,  w,          zc],
      [x,  a1,         zc + dt * u1],
      [x,  a2,         zc + dt * u2],
      [x,  a3,         zc + dt * u3],
      [x,  wt,         zt],
      [x,  wt * 0.66,  zt + cr * 0.72],
      [x,  0,          zt + cr],
      [x, -wt * 0.66,  zt + cr * 0.72],
      [x, -wt,         zt],
      [x, -a3,         zc + dt * u3],
      [x, -a2,         zc + dt * u2],
      [x, -a1,         zc + dt * u1],
      [x, -w,          zc],
      [x, -w,          zc],
      [x, -b1,         zc - db * d1],
      [x, -b2,         zc - db * d2],
      [x, -wb,         zb],
      [x, -wb,         zb],
      [x,  0,          zb - 0.015],
      [x,  wb,         zb],
      [x,  wb,         zb],
      [x,  b2,         zc - db * d2],
      [x,  b1,         zc - db * d1],
      [x,  w,          zc]
    ];
  }

  /* ---- symmetric aerofoil half thickness, NACA four-digit --------------- */
  function yt(s, tc) {
    return tc * (1.4845 * Math.sqrt(s) - 0.6300 * s - 1.7580 * s * s
               + 1.4215 * s * s * s - 0.5075 * s * s * s * s);
  }

  /* one aerofoil ring in a horizontal plane: TE over the top to LE, back
     under to TE.  Cosine spacing puts the points where the curvature is. */
  function foilRing(xLE, chord, y, z, tc, m) {
    var p = [], i, s, x, h;
    for (i = 0; i <= m; i++) {
      s = 0.5 * (1 + Math.cos(Math.PI * i / m));
      x = xLE - s * chord; h = yt(s, tc) * chord;
      p.push([x, y, z + h]);
    }
    for (i = m - 1; i >= 0; i--) {
      s = 0.5 * (1 + Math.cos(Math.PI * i / m));
      x = xLE - s * chord; h = yt(s, tc) * chord;
      p.push([x, y, z - h]);
    }
    return p;
  }

  /* the same ring rotated into a canted fin plane: h runs up the fin, ca/sa
     are the cosine and sine of the fin's angle from horizontal.           */
  function finRing(xLE, chord, h, tc, m, ca, sa, y0, z0) {
    var p = [], i, s, x, t;
    for (i = 0; i <= m; i++) {
      s = 0.5 * (1 + Math.cos(Math.PI * i / m));
      x = xLE - s * chord; t = yt(s, tc) * chord;
      p.push([x, y0 + h * ca - t * sa, z0 + h * sa + t * ca]);
    }
    for (i = m - 1; i >= 0; i--) {
      s = 0.5 * (1 + Math.cos(Math.PI * i / m));
      x = xLE - s * chord; t = yt(s, tc) * chord;
      p.push([x, y0 + h * ca + t * sa, z0 + h * sa - t * ca]);
    }
    return p;
  }

  /* rounded-rectangle ring in the y-z plane at station x */
  function rrectRing(x, cy, cz, hw, hh, n, e) {
    var p = [], i, a;
    for (i = 0; i < n; i++) {
      a = i / n * Math.PI * 2;
      p.push([x, cy + hw * sgnpow(Math.cos(a), e), cz + hh * sgnpow(Math.sin(a), e)]);
    }
    return p;
  }

  function circRing(x, cz, r, n) {
    var p = [], i, a;
    for (i = 0; i < n; i++) {
      a = i / n * Math.PI * 2;
      p.push([x, r * Math.cos(a), cz + r * Math.sin(a)]);
    }
    return p;
  }

  function strut(THREE, mat, a, b, r, seg) {
    var dx = b[0] - a[0], dy = b[1] - a[1], dz = b[2] - a[2];
    var len = Math.sqrt(dx * dx + dy * dy + dz * dz) || 0.01;
    var m = new THREE.Mesh(new THREE.CylinderGeometry(r, r, len, seg || 8), mat);
    m.position.set((a[0] + b[0]) / 2, (a[1] + b[1]) / 2, (a[2] + b[2]) / 2);
    m.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0),
      new THREE.Vector3(dx / len, dy / len, dz / len));
    return m;
  }

  function box(THREE, mat, sx, sy, sz, px, py, pz) {
    var m = new THREE.Mesh(new THREE.BoxGeometry(sx, sy, sz), mat);
    m.position.set(px, py, pz);
    return m;
  }

  /* ======================================================================
     PAINTWORK
     An airframe is a mosaic, not a flat colour.  Two canvases: one wrapped
     round the fuselage, one tiled across the flying surfaces.  Both carry
     base camouflage, panel seams, rivet rows and weathering that is heavier
     low down and behind the exhaust, as the house contract requires.

     The seams are drawn ZIGZAG.  Every removable panel on a low-observable
     airframe has a sawtooth edge so it never presents a straight line square
     to a radar; on the real aeroplane it is the first thing you notice up
     close, and it is what stops this reading as a 1990s jet.
     ====================================================================== */
  var texCache = null;

  function rngFor(seed) {
    var s = (seed >>> 0) || 1;
    return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; };
  }

  /* a serrated seam from (x0,y0) to (x1,y1) */
  function zig(g, x0, y0, x1, y1, amp, wave) {
    var dx = x1 - x0, dy = y1 - y0, L = Math.sqrt(dx * dx + dy * dy);
    if (L < 1) return;
    var ux = dx / L, uy = dy / L, nx = -uy, ny = ux;
    var n = Math.max(2, Math.round(L / wave)), i, t, s;
    g.beginPath();
    for (i = 0; i <= n; i++) {
      t = i / n * L; s = (i % 2 ? amp : -amp);
      if (i === 0 || i === n) s = 0;
      if (i === 0) g.moveTo(x0 + ux * t + nx * s, y0 + uy * t + ny * s);
      else g.lineTo(x0 + ux * t + nx * s, y0 + uy * t + ny * s);
    }
    g.stroke();
  }

  /* a closed sawtooth-edged panel */
  function zigPanel(g, x, y, w, h, amp, wave, fill) {
    var pts = [], i, n;
    n = Math.max(2, Math.round(w / wave));
    for (i = 0; i <= n; i++) pts.push([x + w * i / n, y + (i % 2 ? amp : 0)]);
    n = Math.max(2, Math.round(h / wave));
    for (i = 1; i <= n; i++) pts.push([x + w - (i % 2 ? amp : 0), y + h * i / n]);
    n = Math.max(2, Math.round(w / wave));
    for (i = 1; i <= n; i++) pts.push([x + w - w * i / n, y + h - (i % 2 ? amp : 0)]);
    n = Math.max(2, Math.round(h / wave));
    for (i = 1; i < n; i++) pts.push([x + (i % 2 ? amp : 0), y + h - h * i / n]);
    g.beginPath();
    g.moveTo(pts[0][0], pts[0][1]);
    for (i = 1; i < pts.length; i++) g.lineTo(pts[i][0], pts[i][1]);
    g.closePath();
    if (fill) { g.fillStyle = fill; g.fill(); }
    g.stroke();
  }

  function rivets(g, x0, y0, x1, y1, step) {
    var dx = x1 - x0, dy = y1 - y0, L = Math.sqrt(dx * dx + dy * dy);
    var n = Math.floor(L / step), i;
    for (i = 0; i <= n; i++) {
      g.fillRect(x0 + dx * i / n - 0.8, y0 + dy * i / n - 0.8, 1.7, 1.7);
    }
  }

  /* -------- fuselage sheet.  u: nose 0 -> tail 1.  v: 0 chine, 0.25 top
     deck, 0.5 far chine, 0.75 belly. ------------------------------------- */
  function fuseCanvas() {
    var W = 1024, H = 512, i, k;
    var cv = document.createElement("canvas");
    cv.width = W; cv.height = H;
    var g = cv.getContext("2d");
    var R = rngFor(20261);

    g.fillStyle = "#768086"; g.fillRect(0, 0, W, H);

    /* upper surfaces darker, belly lighter - every tactical grey scheme */
    var gt = g.createLinearGradient(0, 0, 0, H);
    gt.addColorStop(0.00, "rgba(0,0,0,0.00)");
    gt.addColorStop(0.25, "rgba(28,34,38,0.30)");
    gt.addColorStop(0.50, "rgba(0,0,0,0.00)");
    gt.addColorStop(0.75, "rgba(255,255,255,0.20)");
    gt.addColorStop(1.00, "rgba(0,0,0,0.00)");
    g.fillStyle = gt; g.fillRect(0, 0, W, H);

    /* LO panel patchwork: neighbouring panels cure to slightly different
       shades and that mottle is the signature of the coating */
    g.lineWidth = 1.0;
    for (i = 0; i < 22; i++) {
      var px = R() * W * 0.96, py = R() * H * 0.94;
      var pw = 60 + R() * 190, ph = 34 + R() * 96;
      g.globalAlpha = 0.05 + R() * 0.07;
      g.strokeStyle = "rgba(24,28,32,0.40)";
      zigPanel(g, px, py, pw, ph, 3.2, 17,
        R() < 0.42 ? C_RAM : (R() < 0.6 ? C_TRIM : C_TOP));
    }
    g.globalAlpha = 1;

    /* frame seams across the body, stringer seams along it - all serrated */
    g.strokeStyle = "rgba(18,22,26,0.30)"; g.lineWidth = 1.2;
    var st = [0.055, 0.10, 0.155, 0.215, 0.275, 0.34, 0.405, 0.47, 0.535,
              0.60, 0.665, 0.725, 0.785, 0.845, 0.905, 0.95];
    for (i = 0; i < st.length; i++) zig(g, st[i] * W, 0, st[i] * W, H, 5, 17);
    g.strokeStyle = "rgba(18,22,26,0.22)"; g.lineWidth = 1.1;
    var ln = [0.085, 0.165, 0.335, 0.415, 0.585, 0.665, 0.835, 0.915];
    for (i = 0; i < ln.length; i++) zig(g, 0.03 * W, ln[i] * H, 0.97 * W, ln[i] * H, 4, 19);

    /* bay door outlines on the belly band, and their sawtooth edges */
    g.strokeStyle = "rgba(16,20,24,0.55)"; g.lineWidth = 1.8;
    zigPanel(g, 0.30 * W, 0.615 * H, 0.30 * W, 0.115 * H, 5, 16, null);
    zigPanel(g, 0.30 * W, 0.775 * H, 0.30 * W, 0.115 * H, 5, 16, null);

    /* rivet and fastener rows following the frames */
    g.fillStyle = "rgba(16,20,24,0.26)";
    for (i = 0; i < 30; i++) {
      var ry = R() * H, rx = R() * W * 0.72;
      rivets(g, rx, ry, rx + 70 + R() * 190, ry + (R() - 0.5) * 10, 7.5);
    }
    for (i = 0; i < 12; i++) {
      var cx2 = R() * W;
      rivets(g, cx2, 0.05 * H + R() * 0.2 * H, cx2 + (R() - 0.5) * 8, 0.45 * H, 8);
    }

    /* access hatches */
    g.strokeStyle = "rgba(16,20,24,0.34)"; g.lineWidth = 1.0;
    for (i = 0; i < 16; i++) {
      var hx = R() * W, hy = R() * H, hw = 15 + R() * 32, hh = 11 + R() * 20;
      g.globalAlpha = 0.42; zigPanel(g, hx, hy, hw, hh, 2.4, 12, "rgba(0,0,0,0.08)");
      g.globalAlpha = 1;
    }

    /* radome: a different material, always a slightly different grey */
    g.fillStyle = "rgba(70,78,84,0.55)";
    g.fillRect(0, 0, 0.052 * W, H);
    g.strokeStyle = "rgba(16,20,24,0.6)"; g.lineWidth = 2;
    zig(g, 0.052 * W, 0, 0.052 * W, H, 6, 20);

    /* anti-glare panel on the nose deck ahead of the windscreen */
    g.fillStyle = "rgba(30,34,38,0.90)";
    g.beginPath();
    g.moveTo(0.055 * W, 0.222 * H); g.lineTo(0.175 * W, 0.196 * H);
    g.lineTo(0.175 * W, 0.304 * H); g.lineTo(0.055 * W, 0.278 * H);
    g.closePath(); g.fill();

    /* electro-optical aperture panels, low down forward */
    g.fillStyle = "rgba(24,28,32,0.75)";
    for (k = 0; k < 4; k++) {
      g.fillRect((0.09 + k * 0.035) * W, (k % 2 ? 0.70 : 0.30) * H, 16, 11);
    }

    /* weathering.  Heavier low down: rain and hydraulic streaks run to the
       belly and dry there, and every gun-gas and vent stain trails aft. */
    var lb = g.createLinearGradient(0, 0.52 * H, 0, 0.98 * H);
    lb.addColorStop(0, "rgba(30,28,26,0.00)");
    lb.addColorStop(1, "rgba(30,28,26,0.30)");
    g.fillStyle = lb; g.fillRect(0, 0.52 * H, W, 0.46 * H);
    g.fillStyle = "rgba(26,24,22,0.15)";
    for (i = 0; i < 70; i++) {
      var sx = R() * W, sy = 0.42 * H + R() * 0.5 * H;
      g.fillRect(sx, sy, 2 + R() * 5, 16 + R() * 70);
    }
    /* soot behind the exhaust */
    var so = g.createLinearGradient(0.70 * W, 0, W, 0);
    so.addColorStop(0, "rgba(20,18,17,0.00)");
    so.addColorStop(1, "rgba(20,18,17,0.42)");
    g.fillStyle = so; g.fillRect(0.70 * W, 0, 0.30 * W, H);

    /* gun gas stain aft of the port cannon fairing (upper left shoulder) */
    var gg = g.createLinearGradient(0.185 * W, 0, 0.40 * W, 0);
    gg.addColorStop(0, "rgba(22,20,18,0.40)");
    gg.addColorStop(1, "rgba(22,20,18,0.00)");
    g.fillStyle = gg; g.fillRect(0.185 * W, 0.10 * H, 0.215 * W, 0.10 * H);

    /* stencils: unreadable at scale, they read as maintenance markings */
    g.fillStyle = "rgba(206,212,216,0.40)";
    for (i = 0; i < 46; i++) {
      g.fillRect(R() * W, R() * H, 5 + R() * 13, 2);
    }
    g.fillStyle = "rgba(178,44,34,0.50)";
    g.fillRect(0.235 * W, 0.245 * H, 40, 3.5);
    g.fillRect(0.235 * W, 0.735 * H, 40, 3.5);
    g.strokeStyle = "rgba(178,44,34,0.55)"; g.lineWidth = 2;
    g.beginPath();
    g.moveTo(0.20 * W, 0.34 * H); g.lineTo(0.216 * W, 0.30 * H);
    g.lineTo(0.232 * W, 0.34 * H); g.closePath(); g.stroke();

    return cv;
  }

  /* -------- flying-surface sheet.  u: root 0 -> tip 1.  v runs round the
     aerofoil: 0 trailing edge upper, 0.48 leading edge, 0.96 trailing edge
     lower.  Hinge lines are drawn at the v of the real hinge so the
     flaperons and leading-edge flaps read without any extra geometry. --- */
  function panelCanvas() {
    var W = 1024, H = 512, i;
    var cv = document.createElement("canvas");
    cv.width = W; cv.height = H;
    var g = cv.getContext("2d");
    var R = rngFor(77313);

    g.fillStyle = "#768086"; g.fillRect(0, 0, W, H);
    var gt = g.createLinearGradient(0, 0, 0, H);
    gt.addColorStop(0.00, "rgba(26,32,36,0.24)");
    gt.addColorStop(0.46, "rgba(26,32,36,0.24)");
    gt.addColorStop(0.55, "rgba(255,255,255,0.16)");
    gt.addColorStop(1.00, "rgba(255,255,255,0.16)");
    g.fillStyle = gt; g.fillRect(0, 0, W, H);

    /* panel mottle */
    g.lineWidth = 1.0;
    for (i = 0; i < 18; i++) {
      g.globalAlpha = 0.05 + R() * 0.07;
      g.strokeStyle = "rgba(22,26,30,0.38)";
      zigPanel(g, R() * W * 0.92, R() * H * 0.9, 60 + R() * 150, 30 + R() * 70,
        3.0, 16, R() < 0.5 ? C_RAM : C_TRIM);
    }
    g.globalAlpha = 1;

    /* spanwise rib seams */
    g.strokeStyle = "rgba(18,22,26,0.35)"; g.lineWidth = 1.4;
    for (i = 1; i < 12; i++) zig(g, i / 12 * W, 0, i / 12 * W, H, 4.5, 16);

    /* control-surface hinge lines: flaperon 75 per cent chord, leading-edge
       flap 15 per cent chord, on both surfaces */
    g.strokeStyle = "rgba(14,18,22,0.62)"; g.lineWidth = 2.4;
    [0.160, 0.840].forEach(function (v) {
      g.beginPath(); g.moveTo(0.10 * W, v * H); g.lineTo(0.97 * W, v * H); g.stroke();
    });
    g.strokeStyle = "rgba(14,18,22,0.5)"; g.lineWidth = 1.9;
    [0.357, 0.643].forEach(function (v) {
      g.beginPath(); g.moveTo(0.06 * W, v * H); g.lineTo(0.97 * W, v * H); g.stroke();
    });

    /* leading-edge erosion strip, always a lighter bare-ish band */
    g.fillStyle = "rgba(196,202,206,0.20)";
    g.fillRect(0, 0.465 * H, W, 0.035 * H);

    /* fastener rows down every rib */
    g.fillStyle = "rgba(16,20,24,0.24)";
    for (i = 1; i < 12; i++) rivets(g, i / 12 * W, 0.03 * H, i / 12 * W, 0.97 * H, 9);

    /* walkway hatching over the root upper surface */
    g.strokeStyle = "rgba(22,22,22,0.42)"; g.lineWidth = 3;
    g.setLineDash([10, 8]);
    g.beginPath(); g.moveTo(0.02 * W, 0.115 * H); g.lineTo(0.30 * W, 0.115 * H); g.stroke();
    g.beginPath(); g.moveTo(0.02 * W, 0.30 * H); g.lineTo(0.30 * W, 0.30 * H); g.stroke();
    g.setLineDash([]);

    /* weathering: dirt collects on the lower surface and streaks aft */
    g.fillStyle = "rgba(28,26,24,0.13)";
    for (i = 0; i < 46; i++) {
      g.fillRect(R() * W, 0.52 * H + R() * 0.46 * H, 14 + R() * 60, 2 + R() * 5);
    }
    var lb = g.createLinearGradient(0, 0.5 * H, 0, H);
    lb.addColorStop(0, "rgba(30,28,26,0.00)");
    lb.addColorStop(1, "rgba(30,28,26,0.22)");
    g.fillStyle = lb; g.fillRect(0, 0.5 * H, W, 0.5 * H);

    g.fillStyle = "rgba(206,212,216,0.35)";
    for (i = 0; i < 22; i++) g.fillRect(R() * W, R() * H, 5 + R() * 11, 2);
    g.fillStyle = "rgba(178,44,34,0.45)";
    g.fillRect(0.06 * W, 0.20 * H, 34, 3);

    return cv;
  }

  function makeTextures(THREE) {
    if (texCache) return texCache;
    var f = null, p = null;
    try {
      f = new THREE.CanvasTexture(fuseCanvas());
      p = new THREE.CanvasTexture(panelCanvas());
      [f, p].forEach(function (t) {
        t.wrapS = t.wrapT = THREE.RepeatWrapping;
        if (THREE.sRGBEncoding !== undefined) t.encoding = THREE.sRGBEncoding;
        t.anisotropy = 8;
      });
    } catch (e) { f = null; p = null; }
    texCache = { fuse: f, panel: p };
    return texCache;
  }

  /* ======================================================================
     MATERIALS - exactly three tiers
     ====================================================================== */
  function mats(THREE, C) {
    var T = makeTextures(THREE);
    function sk(tex) {
      var m = new THREE.MeshStandardMaterial({
        color: 0xffffff, roughness: 0.87, metalness: 0.08,
        side: THREE.DoubleSide });
      if (tex) m.map = tex; else m.color.setHex(C_SKIN);
      return m;
    }
    return {
      /* 1. SKIN */
      skin: sk(T.fuse),
      panel: sk(T.panel),
      team: new THREE.MeshStandardMaterial({
        color: C && C.team !== undefined ? C.team : 0x3f7fd0,
        roughness: 0.80, metalness: 0.06, side: THREE.DoubleSide }),
      /* 2. METAL */
      metal: new THREE.MeshStandardMaterial({
        color: 0x8d949a, roughness: 0.52, metalness: 0.55, side: THREE.DoubleSide }),
      dark: new THREE.MeshStandardMaterial({
        color: 0x2b2f33, roughness: 0.58, metalness: 0.45, side: THREE.DoubleSide }),
      burn: new THREE.MeshStandardMaterial({
        color: 0x3a3a38, roughness: 0.62, metalness: 0.45, side: THREE.DoubleSide }),
      void_: new THREE.MeshStandardMaterial({
        color: 0x0d0f11, roughness: 0.62, metalness: 0.38, side: THREE.DoubleSide }),
      rubber: new THREE.MeshStandardMaterial({
        color: 0x1b1d1f, roughness: 0.95, metalness: 0.04, side: THREE.DoubleSide }),
      /* 3. GLASS - the F-35 canopy is gold-filmed, not clear */
      glass: new THREE.MeshPhysicalMaterial({
        color: 0x574a2c, roughness: 0.09, metalness: 0.46,
        transparent: true, opacity: 0.81, side: THREE.DoubleSide,
        clearcoat: 1.0, clearcoatRoughness: 0.05 }),
      lens: new THREE.MeshPhysicalMaterial({
        color: 0x232c33, roughness: 0.06, metalness: 0.35,
        transparent: true, opacity: 0.86, side: THREE.DoubleSide,
        clearcoat: 1.0, clearcoatRoughness: 0.04 })
    };
  }

  /* ======================================================================
     FUSELAGE STATIONS
     x, w(chine), zc, zt, wt, crown, zb, wb   - all metres, nose first.
     The mid body is deliberately DEEP: 1.90 m from deck to belly on a
     3.58 m beam.  That squat, slab-sided middle is where the weapons bays
     live and it is the whole reason the aeroplane looks the way it does.
     ====================================================================== */
  var STA = [
    [ 7.90, 0.05,  0.00, 0.03, 0.03, 0.00, -0.03, 0.03],
    [ 7.62, 0.17, -0.03, 0.10, 0.07, 0.00, -0.15, 0.07],
    [ 7.25, 0.32, -0.06, 0.18, 0.13, 0.01, -0.29, 0.14],
    [ 6.80, 0.48, -0.08, 0.26, 0.20, 0.01, -0.42, 0.22],
    [ 6.30, 0.66, -0.09, 0.33, 0.27, 0.02, -0.55, 0.30],
    [ 5.75, 0.84, -0.09, 0.39, 0.34, 0.02, -0.67, 0.38],
    [ 5.15, 1.01, -0.07, 0.44, 0.41, 0.02, -0.78, 0.46],
    [ 4.55, 1.16, -0.05, 0.48, 0.48, 0.02, -0.88, 0.53],
    [ 3.95, 1.30, -0.03, 0.52, 0.55, 0.02, -0.97, 0.60],
    [ 3.35, 1.43, -0.01, 0.56, 0.62, 0.02, -1.04, 0.67],
    [ 2.75, 1.55,  0.01, 0.60, 0.69, 0.03, -1.10, 0.74],
    [ 2.15, 1.65,  0.03, 0.64, 0.76, 0.03, -1.14, 0.80],
    [ 1.55, 1.72,  0.04, 0.67, 0.82, 0.03, -1.17, 0.85],
    [ 0.90, 1.77,  0.05, 0.69, 0.87, 0.03, -1.19, 0.89],
    [ 0.25, 1.79,  0.06, 0.70, 0.90, 0.03, -1.19, 0.91],
    [-0.40, 1.78,  0.06, 0.71, 0.90, 0.03, -1.18, 0.91],
    [-1.05, 1.74,  0.06, 0.70, 0.89, 0.03, -1.14, 0.89],
    [-1.70, 1.67,  0.06, 0.69, 0.86, 0.03, -1.08, 0.85],
    [-2.35, 1.58,  0.05, 0.67, 0.82, 0.03, -1.00, 0.80],
    [-3.00, 1.46,  0.05, 0.64, 0.77, 0.03, -0.91, 0.74],
    [-3.65, 1.33,  0.04, 0.61, 0.71, 0.02, -0.81, 0.67],
    [-4.30, 1.19,  0.03, 0.57, 0.65, 0.02, -0.71, 0.60],
    [-4.95, 1.06,  0.02, 0.56, 0.60, 0.02, -0.68, 0.55],
    [-5.60, 0.94,  0.01, 0.56, 0.56, 0.01, -0.65, 0.51],
    [-6.25, 0.82,  0.00, 0.57, 0.53, 0.01, -0.62, 0.48],
    [-6.80, 0.72,  0.00, 0.58, 0.50, 0.00, -0.60, 0.45]
  ];

  /* wing plan - trapezoid, straight leading edge, NO root extension */
  var W_ROOT_LE = 2.05, W_LE_TAN = 0.6745;   /* 34 degrees */
  var W_ROOT_C = 6.45, W_C_SLOPE = 0.9044;
  var W_TIP = 5.35;

  /* ======================================================================
     BUILD
     ====================================================================== */
  function build(THREE, M, C) {
    var g = new THREE.Group();
    var P = mats(THREE, C);
    var i;

    /* ---------------------------------------------------- fuselage ------ */
    var sect = resample(STA, 30), rings = [];
    for (i = 0; i < sect.length; i++) rings.push(chineRing(sect[i]));
    g.add(new THREE.Mesh(skin(THREE, rings, CHINE_SKIP, true, true), P.skin));

    /* dorsal spine aft of the canopy - carries the refuelling receptacle */
    g.add(new THREE.Mesh(M.loft(THREE, [
      { x: 0.40, w: 0.30, h: 0.05, zc: 0.70, sq: 0.60 },
      { x: 1.00, w: 0.36, h: 0.07, zc: 0.72, sq: 0.60 },
      { x: 1.60, w: 0.40, h: 0.09, zc: 0.73, sq: 0.60 },
      { x: 2.20, w: 0.40, h: 0.10, zc: 0.71, sq: 0.60 },
      { x: 2.62, w: 0.33, h: 0.08, zc: 0.68, sq: 0.60 }
    ], 14), P.skin));

    /* ------------------------------------- internal weapons bay bulges --
       Two long blisters either side of the keel.  This is the "chunky mid
       body with a deep weapons bay bulge" - the bays are why the aeroplane
       has a belly at all, so they must read from the side and from below. */
    var bay = [
      { x: -1.55, w: 0.34, h: 0.09, zc: -1.14, sq: 0.50 },
      { x: -0.90, w: 0.42, h: 0.12, zc: -1.20, sq: 0.50 },
      { x:  0.00, w: 0.45, h: 0.13, zc: -1.24, sq: 0.50 },
      { x:  1.10, w: 0.45, h: 0.13, zc: -1.22, sq: 0.50 },
      { x:  1.90, w: 0.40, h: 0.11, zc: -1.16, sq: 0.50 },
      { x:  2.45, w: 0.30, h: 0.08, zc: -1.08, sq: 0.50 }
    ];
    var bayG = M.loft(THREE, bay, 14);
    bayG.translate(0, 0.50, 0);
    var bayL = new THREE.Mesh(bayG, P.skin);
    var bayR = bayL.clone(); bayR.scale.y = -1;
    g.add(bayL); g.add(bayR);

    /* ------------------------------------------------- mirrored halves -- */
    var half = new THREE.Group();

    /* ---- aft boom: carries the canted fin and the all-moving taileron,
       and gives the tail its twin-boom-with-a-nozzle-between look ------- */
    var boomG = M.loft(THREE, [
      { x: -7.00, w: 0.24, h: 0.265, zc: 0.005, sq: 0.55 },
      { x: -6.30, w: 0.29, h: 0.335, zc: 0.005, sq: 0.55 },
      { x: -5.40, w: 0.34, h: 0.400, zc: 0.000, sq: 0.55 },
      { x: -4.40, w: 0.38, h: 0.450, zc: -0.010, sq: 0.55 },
      { x: -3.40, w: 0.42, h: 0.500, zc: -0.020, sq: 0.55 },
      { x: -2.40, w: 0.46, h: 0.535, zc: -0.015, sq: 0.55 }
    ], 16);
    boomG.translate(0, 1.12, 0);
    half.add(new THREE.Mesh(boomG, P.skin));

    /* ---- wing: trapezoid, 34 deg straight LE, taper 0.25, no dihedral,
       and it grows straight out of the chine line -------------------- */
    var wr = [], n = 11, m = 11, f, y, tc;
    for (i = 0; i < n; i++) {
      f = i / (n - 1);
      y = 0.95 + (W_TIP - 0.95) * f;
      tc = 0.086 - 0.038 * f;
      wr.push(foilRing(W_ROOT_LE - W_LE_TAN * y, W_ROOT_C - W_C_SLOPE * y,
                       y, 0.045 - 0.012 * f, tc, m));
    }
    half.add(new THREE.Mesh(skin(THREE, wr, null, false, true), P.panel));

    /* ---- all-moving taileron ----------------------------------------- */
    var tr = [];
    for (i = 0; i < 7; i++) {
      f = i / 6;
      y = 0.80 + 2.50 * f;
      tr.push(foilRing(-4.20 - 0.6745 * (y - 0.80), 3.05 - 0.880 * (y - 0.80),
                       y, -0.02 - 0.10 * f, 0.072 - 0.024 * f, 9));
    }
    half.add(new THREE.Mesh(skin(THREE, tr, null, false, true), P.panel));

    /* ---- canted fin.  25 degrees out of vertical: the pair reads as a
       shallow V from dead ahead and is the tell of the whole generation. */
    var cant = 65 * D2R, ca = Math.cos(cant), sa = Math.sin(cant);
    var fr = [], h;
    for (i = 0; i < 8; i++) {
      f = i / 7;
      h = -0.30 + 2.40 * f;
      fr.push(finRing(-2.30 - 0.930 * (h + 0.30), 3.35 - 0.780 * (h + 0.30),
                      h, 0.074 - 0.026 * f, 9, ca, sa, 1.05, 0.47));
    }
    half.add(new THREE.Mesh(skin(THREE, fr, null, false, true), P.panel));

    /* ---- diverterless supersonic intake -------------------------------
       The bump does the work a splitter plate and a set of ramps used to
       do, so there is no gap between the cowl and the fuselage - just a
       swelling in the skin ahead of a forward-raked lip.                 */
    var cowl = [], cs = [
      [3.30, 1.50, -0.16, 0.30, 0.50, 1.00],
      [2.90, 1.52, -0.16, 0.31, 0.50, 0.55],
      [2.40, 1.54, -0.14, 0.32, 0.48, 0.22],
      [1.90, 1.55, -0.10, 0.32, 0.44, 0.05],
      [1.40, 1.56, -0.05, 0.30, 0.38, 0.00],
      [0.85, 1.55,  0.01, 0.25, 0.30, 0.00]
    ];
    for (i = 0; i < cs.length; i++) {
      var c0 = cs[i], rr = rrectRing(0, c0[1], c0[2], c0[3], c0[4], 20, 0.58), k2;
      for (k2 = 0; k2 < rr.length; k2++) {
        /* rake: the outboard lower corner of the lip leads */
        rr[k2][0] = c0[0] + c0[5] * (0.26 * (rr[k2][1] - c0[1]) / c0[3]
                                   - 0.11 * (rr[k2][2] - c0[2]) / c0[4]);
      }
      cowl.push(rr);
    }
    half.add(new THREE.Mesh(skin(THREE, cowl, null, false, false), P.skin));

    /* the duct behind the lip, so the inlet reads as a hole and not a blob */
    var duct = [];
    for (i = 0; i < 3; i++) {
      duct.push(rrectRing(3.16 - i * 0.62, 1.50, -0.16,
                          0.245 - i * 0.03, 0.425 - i * 0.05, 20, 0.58));
    }
    half.add(new THREE.Mesh(skin(THREE, duct, null, false, true), P.void_));

    /* the bump itself */
    var bump = new THREE.Mesh(new THREE.SphereGeometry(1, 16, 10), P.skin);
    bump.scale.set(0.95, 0.30, 0.46);
    bump.position.set(3.86, 1.24, -0.16);
    half.add(bump);
    var bump2 = new THREE.Mesh(new THREE.SphereGeometry(1, 12, 8), P.skin);
    bump2.scale.set(0.55, 0.22, 0.30);
    bump2.position.set(4.55, 1.16, -0.20);
    half.add(bump2);

    /* ---- GAU-22 cannon fairing: on the PORT shoulder only, which is why
       the aeroplane is not left-right symmetrical from above ---------- */
    var gunG = M.loft(THREE, [
      { x: 1.75, w: 0.10, h: 0.08, zc: 0.59, sq: 0.50 },
      { x: 2.05, w: 0.18, h: 0.14, zc: 0.58, sq: 0.50 },
      { x: 2.45, w: 0.20, h: 0.16, zc: 0.56, sq: 0.50 },
      { x: 2.85, w: 0.16, h: 0.13, zc: 0.53, sq: 0.50 },
      { x: 3.15, w: 0.06, h: 0.05, zc: 0.50, sq: 0.50 }
    ], 12);
    gunG.translate(0, 1.20, 0);
    g.add(new THREE.Mesh(gunG, P.skin));
    g.add(box(THREE, P.void_, 0.05, 0.10, 0.09, 3.12, 1.19, 0.50));

    /* ---- team flash: fin cap, wing cuff, boom band --------------------- */
    var flash = [];
    for (i = 0; i < 2; i++) {
      h = 1.42 + i * 0.46;
      flash.push(finRing(-2.30 - 0.930 * (h + 0.30) + 0.010,
                         (3.35 - 0.780 * (h + 0.30)) * 1.012,
                         h, (0.074 - 0.026 * (h + 0.30) / 2.40) * 1.09,
                         9, ca, sa, 1.05, 0.47));
    }
    half.add(new THREE.Mesh(skin(THREE, flash, null, false, false), P.team));

    var cuff = [];
    for (i = 0; i < 2; i++) {
      y = 4.30 + i * 0.58;
      f = (y - 0.95) / (W_TIP - 0.95);
      cuff.push(foilRing(W_ROOT_LE - W_LE_TAN * y + 0.008,
                         (W_ROOT_C - W_C_SLOPE * y) * 1.012,
                         y, 0.045 - 0.012 * f, (0.086 - 0.038 * f) * 1.10, 11));
    }
    half.add(new THREE.Mesh(skin(THREE, cuff, null, false, false), P.team));

    var bandG = M.loft(THREE, [
      { x: -6.45, w: 0.290, h: 0.333, zc: 0.005, sq: 0.55 },
      { x: -6.05, w: 0.316, h: 0.367, zc: 0.005, sq: 0.55 }
    ], 16);
    bandG.translate(0, 1.12, 0);
    half.add(new THREE.Mesh(bandG, P.team));

    var halfR = half.clone();
    halfR.scale.y = -1;
    g.add(half); g.add(halfR);

    /* ---------------------------------------------------- canopy -------- */
    var cp = [
      [6.10, 0.13, 0.32, 0.42], [5.85, 0.26, 0.35, 0.60],
      [5.55, 0.38, 0.38, 0.78], [5.20, 0.47, 0.41, 0.92],
      [4.85, 0.53, 0.44, 1.00], [4.50, 0.56, 0.46, 1.04],
      [4.15, 0.56, 0.48, 1.04], [3.80, 0.54, 0.50, 1.00],
      [3.45, 0.49, 0.52, 0.93], [3.10, 0.42, 0.54, 0.84],
      [2.80, 0.33, 0.56, 0.73], [2.55, 0.24, 0.58, 0.65]
    ];
    function domeRing(s, sw, sh) {
      var p = [], j, a;
      for (j = 0; j <= 12; j++) {
        a = Math.PI * j / 12;
        p.push([s[0], s[1] * sw * Math.cos(a),
                s[2] + (s[3] - s[2]) * sh * Math.sin(a)]);
      }
      return p;
    }
    var cr2 = [];
    for (i = 0; i < cp.length; i++) cr2.push(domeRing(cp[i], 1, 1));
    /* skip the closing quad so the canopy is a shell, not a solid lens */
    g.add(new THREE.Mesh(skin(THREE, cr2, [12], false, false), P.glass));

    /* windscreen-to-canopy bow frame */
    var fb = [domeRing(cp[3], 1.06, 1.045), domeRing(cp[3], 1.10, 1.075),
              domeRing([cp[3][0] - 0.13, cp[3][1], cp[3][2], cp[3][3]], 1.06, 1.045)];
    fb[0][0][0] += 0.10; /* nudge the first ring forward for a bow, not a disc */
    for (i = 0; i <= 12; i++) fb[0][i][0] = cp[3][0] + 0.10;
    g.add(new THREE.Mesh(skin(THREE, fb, [12], false, false), P.skin));

    /* canopy sill rails */
    var sillG = M.slab(THREE, [
      [6.05, 0.30], [5.20, 0.40], [4.20, 0.47], [3.20, 0.53], [2.60, 0.57],
      [2.60, 0.50], [3.20, 0.46], [4.20, 0.40], [5.20, 0.33], [6.05, 0.24]
    ], 0.07, "xz");
    var sillL = new THREE.Mesh(sillG, P.skin);
    sillL.position.y = 0.56;
    var sillR = sillL.clone(); sillR.position.y = -0.49;
    g.add(sillL); g.add(sillR);

    /* ---------------------------------------------- cockpit interior ---- */
    g.add(box(THREE, P.void_, 2.05, 0.92, 0.55, 4.62, 0, 0.32));
    g.add(box(THREE, P.dark, 0.30, 0.60, 0.42, 5.42, 0, 0.52));   /* coaming */
    g.add(box(THREE, P.dark, 0.16, 0.52, 0.62, 3.80, 0, 0.66));   /* seat back */
    g.add(box(THREE, P.dark, 0.52, 0.50, 0.12, 4.14, 0, 0.42));   /* pan */
    g.add(box(THREE, P.dark, 0.22, 0.44, 0.20, 3.70, 0, 1.00));   /* headbox */
    var helm = new THREE.Mesh(new THREE.SphereGeometry(0.155, 10, 7), P.metal);
    helm.position.set(4.32, 0, 0.84);
    g.add(helm);
    g.add(box(THREE, P.dark, 0.24, 0.44, 0.30, 4.16, 0, 0.62));   /* torso */

    /* ------------------------------------------------ EOTS turret ------- */
    /* faceted, flat-windowed, hung under the radome - unmistakable */
    var eo = [
      [6.52, 0.10, -0.44, -0.52], [6.12, 0.26, -0.52, -0.75],
      [5.76, 0.34, -0.62, -0.87], [5.36, 0.32, -0.72, -0.93],
      [5.00, 0.19, -0.80, -0.90]
    ], er = [];
    for (i = 0; i < eo.length; i++) {
      er.push(rrectRing(eo[i][0], 0, (eo[i][2] + eo[i][3]) / 2, eo[i][1],
                        (eo[i][2] - eo[i][3]) / 2, 10, 0.42));
    }
    g.add(new THREE.Mesh(skin(THREE, er, null, true, true), P.skin));
    var win = M.slab(THREE, [
      [6.34, -0.53], [5.98, -0.80], [5.52, -0.90], [5.50, -0.80],
      [5.96, -0.70], [6.32, -0.46]
    ], 0.30, "xz");
    var winL = new THREE.Mesh(win, P.lens);
    winL.position.y = 0.30;
    g.add(winL);

    /* ------------------------------------------------ exhaust nozzle ---- */
    var nz = [circRing(-6.55, 0, 0.645, 24), circRing(-7.05, 0, 0.610, 24),
              circRing(-7.45, 0, 0.565, 24), circRing(-7.62, 0, 0.535, 24), []];
    /* the trailing edge of every outer flap is sawtoothed, but the teeth are
       shallow - a deep zigzag reads as battle damage, not low observability */
    for (i = 0; i < 24; i++) {
      var a2 = i / 24 * Math.PI * 2;
      nz[4].push([(i % 2) ? -7.80 : -7.68, 0.525 * Math.cos(a2), 0.525 * Math.sin(a2)]);
    }
    g.add(new THREE.Mesh(skin(THREE, nz, null, false, false), P.burn));

    var inner = M.loft(THREE, [
      { x: -7.74, w: 0.44, h: 0.44, zc: 0, sq: 1 },
      { x: -7.30, w: 0.49, h: 0.49, zc: 0, sq: 1 },
      { x: -6.70, w: 0.56, h: 0.56, zc: 0, sq: 1 }
    ], 20);
    g.add(new THREE.Mesh(inner, P.dark));
    var plug = new THREE.Mesh(new THREE.CircleGeometry(0.44, 20), P.void_);
    plug.rotation.y = -Math.PI / 2;
    plug.position.x = -7.73;
    g.add(plug);

    /* ================================================== undercarriage ====
       Named "gear": render3d.js stows it in cruise and drops it on final. */
    var gear = new THREE.Group();
    gear.name = "gear";

    /* nose leg - single wheel, well forward under the cockpit floor */
    gear.add(strut(THREE, P.metal, [4.58, 0, -0.80], [4.40, 0, -1.24], 0.075, 8));
    gear.add(strut(THREE, P.metal, [4.40, 0, -1.20], [4.28, 0, -1.70], 0.055, 8));
    gear.add(strut(THREE, P.metal, [4.58, 0, -0.86], [4.86, 0, -1.16], 0.040, 6));
    gear.add(box(THREE, P.dark, 0.16, 0.30, 0.14, 4.30, 0, -1.62));
    var nw = new THREE.Mesh(new THREE.CylinderGeometry(0.34, 0.34, 0.21, 16), P.rubber);
    nw.position.set(4.28, 0, -1.71);
    gear.add(nw);
    var nh = new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.15, 0.23, 12), P.metal);
    nh.position.set(4.28, 0, -1.71);
    gear.add(nh);
    gear.add(box(THREE, P.void_, 1.10, 0.46, 0.10, 4.42, 0, -0.83));

    var nd = M.slab(THREE, [
      [4.98, -0.06], [4.98, -0.86], [3.92, -0.80], [3.92, -0.04]
    ], 0.055, "xz");
    var ndL = new THREE.Mesh(nd, P.skin);
    ndL.position.set(0, 0.20, -0.80);
    ndL.rotation.x = -0.30;
    var ndR = ndL.clone(); ndR.position.y = -0.145; ndR.rotation.x = 0.30;
    gear.add(ndL); gear.add(ndR);

    /* main legs */
    var mg = new THREE.Group();
    mg.add(strut(THREE, P.metal, [0.28, 1.02, -1.00], [0.06, 1.28, -1.44], 0.085, 8));
    mg.add(strut(THREE, P.metal, [0.06, 1.28, -1.40], [0.00, 1.32, -1.63], 0.062, 8));
    mg.add(strut(THREE, P.metal, [0.30, 0.86, -1.06], [0.08, 1.26, -1.36], 0.045, 6));
    mg.add(strut(THREE, P.metal, [-0.42, 0.92, -1.02], [0.04, 1.27, -1.34], 0.042, 6));
    mg.add(box(THREE, P.dark, 0.20, 0.16, 0.28, 0.04, 1.30, -1.55));
    var mw = new THREE.Mesh(new THREE.CylinderGeometry(0.42, 0.42, 0.27, 16), P.rubber);
    mw.position.set(0.00, 1.32, -1.63);
    mg.add(mw);
    var mh = new THREE.Mesh(new THREE.CylinderGeometry(0.18, 0.18, 0.29, 12), P.metal);
    mh.position.set(0.00, 1.32, -1.63);
    mg.add(mh);
    mg.add(box(THREE, P.void_, 1.60, 0.52, 0.10, 0.10, 0.98, -1.10));
    var md = M.slab(THREE, [
      [0.95, -1.05], [0.95, -1.96], [-0.80, -1.90], [-0.80, -1.02]
    ], 0.06, "xz");
    var mdm = new THREE.Mesh(md, P.skin);
    mdm.position.set(0, 0.86, 0);
    mdm.rotation.x = -0.22;
    mg.add(mdm);
    var mgR = mg.clone(); mgR.scale.y = -1;
    gear.add(mg); gear.add(mgR);

    g.add(gear);
    return g;
  }

  return { build: build };
})();

UNIT_MODELS["nato_e00_stealthfighter"] = {
  len: 15.70,
  build: function (THREE, M, C) { return HeroF35A.build(THREE, M, C); }
};
